### ISSUE TITLE
Use crypto library

### ISSUE THREAD

**Issue by koraa** [inexorgame/inexor-core#2]
Sauer  implements at least it's own version of the tiger hash and a public/private-key scheme.
Investigate what can be replaced and which external projects to embed.

See for instance:
http://www.cryptopp.com/

**Comment by Fohlen** [comment]
Authkeys will be deprecated and so should it's generation be.

**Comment by Fohlen** [comment]
@a-teammate didn't your branch deprecate this? Can this ticket be closed?

**Comment by Croydon** [comment]
What is the replacement for authkeys?

**Comment by Fohlen** [comment]
OAuth

**Comment by aschaeffer** [comment]
We shouldn't close this ticket as long as the replacement is not implemented.

**Comment by Fohlen** [comment]
This will be deprecated in the new engine. None of the sauer crypto code is used.
