### ISSUE TITLE
Add a download page

### ISSUE THREAD

**Issue by Fohlen** [inexorgame/inexor-core#269]
_From @Fohlen on August 22, 2015 15:20_

Add a download page which points to the following
- Link to the source (latest release)
- Links to the latest windows binaries (nightly)
- Asks linux folks to compile themself (wiki/build)
- Asks linux folks to provide binaries
- Asks OSX people to provide binaries

_Copied from original issue: inexor-game/website#18_

**Comment by Fohlen** [comment]
The upcoming download page in my branch will include a ajax-crafted search of all the files available.
Depending on the name, a specific icon is chosen from fa's icon list (OSX, Win, Linux).
By default the latest master bundles are shown, but one will be able to search for a specific revision or branch with the search function :100:

**Comment by Fohlen** [comment]
@aschaeffer what is the status of https://nightly.inexor.org
@a-teammate how difficult will it be to enable AppVeyor to upload nightlies again? Can we do that in the near future?

**Comment by Croydon** [comment]
My Travis Docker work is also able to upload nightlies, only things missing are the FTP data in the Travis settings (website).

**Comment by Fohlen** [comment]
The page will render https://github.com/inexorgame/code/wiki/Install-Inexor-in-five-minutes#installation-guide in a nice bootstrap accordeon. Maybe @terencode would like to work on this?
My vision is that:

- you click the download button, there you can select between 3 symbols (platforms)
- it will forward you (via anchor) to the respective section in the article

**Comment by terencode** [comment]
@Fohlen yes I'm up to the task. 

_Sent from my OnePlus A0001 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by terencode** [comment]
@Fohlen we could take exemple on some parts of https://v4-alpha.getbootstrap.com/examples/carousel/#myCarousel

**Comment by Croydon** [comment]
@movabo @Fohlen @IAmNotHanni  does someone wants to do this today or tomorrow?

**Comment by Fohlen** [comment]
@IAmNotHanni please also update the wiki article at https://github.com/inexorgame/inexor-core/wiki/Install-Inexor-in-five-minutes

**Comment by Croydon** [comment]
https://github.com/inexorgame/site/pull/10
