### ISSUE TITLE
Add windows setup

### ISSUE THREAD

**Issue by Fohlen** [inexorgame/inexor-core#277]
In addition to the linux packages @bebehei is currently working on, we should think about offering a windows setup executable, or even add Inexor to the chocolate gallery, which is Windows 8/10++ approach for handling 3rd party software.
Although Inexor is still in a early Alpha stage, we should consider that the most reliable source for feedback, suggestions and improvement comes from players themselves. A game with little/no player base at all isn't easy to get ahead with on Steam, for example.
This is why we should minimize any efforts to download, install and run Inexor.
Considering the VS-15 issue, such a setup would allow us to ship the redistributable package as well

**Comment by Croydon** [comment]
Heavily related to #138. I'm not even sure if we need a separate issue.
The issue with VS was that we needed the redistributable package installed on (some of) the end user pcs, @a-teammate fixed that.

I'm not sure if a package manager like Chocolatey can bring us any further on Windows. I consider it more as another dependency, which requires by itself .NET Framework 4.0. We would need to find a way to install both automatically, but then we have obviously a good installer by ourselves, so we don't need a package manager anymore, right?

**Comment by Fohlen** [comment]
Chocolate will be default on windows and included in their service pack along with .NET 
Using a package manager minimizes our setup and powers us with an easy way to consistently deliver updates, which we don't want to do ourselves...

**Comment by Croydon** [comment]
We can't afford to exclude Windows 7

**Comment by a-teammate** [comment]
An installer could be better done with CPack: exe installer, deb, rpm, osx-bundles, archives all from one.

**Comment by a-teammate** [comment]
This seems like a **good first bug** from here on:
What do we want to do in the installer?
Pseudocode for a possible [NSIS script](http://nsis.sourceforge.net):

```
// 1. Version check:
If not Windows-version >= windows7:
    "Sorry, no support planned. try it, if you want to."
If not Architecture == x64:
     "Sorry, currently no prebuilt windows binaries available. Tell the Inexor Crew to let them kick off a build."

// 2. Install node.js as the first step
If not node.js in PATH:
    download node.js-installer (x64)
    msiexec node.js installer
    add node.js to PATH

// 3. Execute node.js to install inexor-flex
lf not `inexor` (or inexor-flex??) in PATH:
    execute `npm install inexor-flex`
    add inexor-flex to PATH
```

For 2. http://nsis.sourceforge.net/Embedding_other_installers could be used as example.
The rest may get solved through heavy googling.. :)

**Comment by Fohlen** [comment]
this will also need #456 on Windows!

**Comment by Fohlen** [comment]
I do think that @a-teammate wrote an installer? Can this be closed?

**Comment by a-teammate** [comment]
https://www.youtube.com/watch?v=M6JaWjZKyW4
this could serve as version 2 installer, as soon as we got some more elementary tasks closed (regarding the overall structure again)
