### ISSUE TITLE
Storyboard/Theme

### ISSUE THREAD

**Issue by MartinMuzatko** [inexorgame/inexor-core#304]
Hello there!

I'd really love to develop a theme or storyboard we can use as a base for all our assets.
Our userbase/contributors except for the core team doesn't quite know what inexor is centered around, theme and story related.

So far I only have some insider information that I got while talking to the core team. I'd love to open a discussion for said infos and, if thoroughly discussed and carefully put together, I'd open a wiki page for that. So other contributors can build assets around that theme.

If you think it is way too early to think about something like a theme, please allow for some discussion and afterwards close this issue if you think it is too early to talk about that.
### Gametitle

Inexor means "In exorbitance".
Which I'd translate to "too much". The question here is of what? Sauerbraten? Or [drugs as suggested here](https://piratenpad.de/p/893u2jun2309ijomk2390ojsfakdjhfabsdfykxhdf)?

Our alpha release title are also centered around several different drugs and their chemical name - which I think is a great idea to describe which features got in.

I don't like to be a nitpicker, but this sounds like promoting drug abuse - of  course in a funny way. So more explanation is required. In the end, Sauerbraten is also just a funny name for that project.
### Storyboard

Today on mumble, someone explained the story they thought of so far. Which is about our Protagonists (Ironsnout, Mr. Fixit and Inky) to sit in a self-help group together. I'd imagine this [to be like this](https://www.youtube.com/watch?v=uxeR95aYer0) which is a pretty funny intro to start the game with. However, more information on that is required.
### Theme

All these bits of informations lead to a core theme we could build upon. This allows us to bring the story to our maps, the textures, the features and also the ingame GUI.

Sauerbraten has all different kinds of maps, which is great because it offers a great deal of variety. a_teammate told me about his vision of the game UI to be trippy and colorful. The latest version can be found on our [ui-prototype repo](https://inexor-game.github.io/ui-prototype/misan/dist/index.html#Game).

I love to get some stories into my maps. For my Sauerbraten maps, the background story was always a bit more serious. For instance:

> Xenon is based on nature catastrophies that lead to flood the lands and leave weird blue moss after the water has settled. The people that explored the land discovered that they can use this glowing moss to turn it into biomass/biofuel. Which is why there is a great war now centered around this scientific outpost in xenon.

To go a bit further, I try to connect my maps with stories ([like Pixar does](http://www.pixartheory.com/)).

Please let me know what you guys think.

**Comment by a-teammate** [comment]
Hey, sorry for not responding here.
I started a [Wiki page](https://github.com/inexorgame/inexor-core/wiki/The-Main-Theme), stating the current state of our brain-storming mumble sessions.

Could you put the youtube link to the wiki page? It pretty much gets the idea :)
Maybe we should refactor that wiki page that the storyline is a distinct point as well

**Comment by MartinMuzatko** [comment]
The wiki page pretty much gets the main theme and explains everything required to shape the future of the game. Thanks a lot for taking the time to write it down. This solves the issue for now.

**Comment by Croydon** [comment]
Not sure why this issue didn't catch my attention, but I tried to have this discusion in #481 

The comments there drifted away to "should we try to win the Sauerbraten community" over and it didn't really got much time at the Hackathon when I recall correctly.

I still have the opinion as explained in #481 and oppose the theme as currently described in the wiki.

When I want to have a colorful game I can just start to contribute to Red Eclipse and drop Inexor, but I want to "stay sauer, keeps better".

**Comment by a-teammate** [comment]
Red eclipses theme has its own issues, which are not related to it trying to be colorful (does it really want to do that? O.o)

**How do you define the Sauerbraten theme?** is the question here. Through the look of the maps? Through the look of the UI? The soundtrack?

The Sauerbraten content is naturally grown. The particular look is just the composition of many different looks because many different people threw their ideas together. Maybe the Doom theme became prominent at some places, since a lot of content comes from there, but not that much actually.

And how would us defining a main theme change that? In fact, it probably won't. Even the opposite: making content distributable will make that chaotic collection of different ideas and themes grow even faster.

Hence the parts one would notice such a main theme is really really limited. The default soundtrack, the default UI, maybe some default textures and maps, but probably not even that.

The UI is going to be dropped. Should the new one be in a gray pattern? Why change the UI then in the first place. If it is changing to a completely new base, it does not make sense to me to design it the very same way the old one was, except if the old design and layout was particularly intuitive and a unique feature in the world of games.

What I think is:
* we want to preserve the collection of naturally grown themes.
* Some key elements will be moved to the "Main Theme"
     * simply because these parts are new and it would not make sense to aim for the old style if it isn't particularly outstanding.

I think that a lot of Sauerbraten people share your opinion, though. They stick to the game because it never changes, but always provides.
But that is why the other issue drifted away: Inexor needs to be different, since it wants a new part of the cake. I just don't think that Sauerbraten theme make it unique, but its ideas.

**Comment by MartinMuzatko** [comment]
I think those are two separate issues you are concerned with. 

One is about the core game mechanics that make Sauer the Sauer we love and which we want to keep but also offer capabilities to let users extend it with their own mechanisms, gamemodes, weapons and other game content. It becomes a matter of how flexible the game contents are. In Sauerbraten a lot of things (gamemode, weapons, core mechanics) are pretty much set in stone. Inexor would allow users to define their own rules. Still- you still need a major default gameplay, and this is where we stay true to Sauerbraten in terms of core mechanics. To what level this can be altered by the user for which gamemode has yet to be defined. There were [very loose concepts ](https://piratenpad.de/p/893u2jun2309ijomk2390ojsfakdjhfabsdfykxhdf)of specific attributes of the characters, similar to how Team Fortress or Overwatch is oriented, but this can work as a plugin, not as a must. This is as far as I understand the goals of the project are. Please correct me if this is different from what you would want.

The other concern is about the theme we want to give Inexor.
Even though Sauerbraten is really flexible and does not have a very prominent  "public face" due to its diversity in all its contents, there are still properties that express the main theme of the game. The menu style, music, projectile particles, weapon-, map- and playermodels all depict a common theme and style that Sauerbraten evolved in its years of development. What is both great and bad about Sauerbraten, is about how open it is. By looking at the game content, you wouldn't tell whether the game is heading more in a medieval, scifi or comic-like style, since it unifies all of it. We can (and I think we want to) keep it like that. 

Other sandbox games also manage to offer a diversity of content, but still have a main theme. E.g. Little big planet also maintains a series of textures from many themes, but they have found their "creative way" of displaying the menus, how playermodels behave, etc.
There are many ways to make a game colorful, and in the way that Sauerbraten has found its way to be diverse and colorful, we can make Inexor our own way of colorful. I very much like the idea of Inexor expressing itself with a vibrant, surreal but still charming main theme. As this exactly depicts the positively weird bunch of people I meet everyday on Sauerbraten, or the people working on creating new content or mods :)
Our team also consists of a very diverse and broad spectrum of life experiences.
I'm trying to warm up with how drugs are part of our theme. I think this is only an exaggeration to what kind of content we are aiming for. 

What key indicators are you concerned about exactly when we talk about a "colorful game"?
A game can express itself in many ways other than the core engine concepts that make up the gameplay. I think @a-teammate tried to refer more about the general feeling that the game should convey through many more aspects like the UI, textures and maps, rather than changing major engine details like red eclipse did. I also believe we are more talking about what possibilities we want, rather than what we want to set in stone. AFAIK Inexor is a sandbox after all and you can implement whatever game mechanics, modes and weapons that you want with the capabilities of Inexor, but the core gameplay and capabilities can and will remain the same. On the contrary, Red Eclipse defined for you that there are double jumps, slower movement, etc. 

There we may need to better define these details, so we do not think that we are locking ourselves into anything.
