### ISSUE TITLE
Refactor gameserver code

### ISSUE THREAD

**Issue by a-teammate** [inexorgame/inexor-core#320]
_Disclaimer: This is actually a duplicate issue of #170 but reformulated_
### The current gameserver code

The current gameserver code is sparkled in a lot of places.
You can get a list of source files the server uses (.cpp only, .hpp not listed) in the `inexor/server/CMakeLists.txt` (In contrast to those the client uses listed in `inexor/client/CMakeLists.txt`).  
Some files get solely splitted by defining the macro "STANDALONE" before compiling the server.
### A better design

A better design would have all (or at least a lot/most) server stuff in the `inexor/server/` folder.
(Inexor client stuff needs a lot more refactoring if we want to divide everything into logical modules, so its not part of this issue)

This would require the following steps:
- Add the lines to the `inexor/server/CMakeLists.txt` which tells it to search this folder for .cpp files
  - `declare_module(` iirc but could be checked from `cmake/functions.cpp` which will replace the old hardcoded list of source files in this CMakeLists.txt
- Move all code for the server into new files in `inexor/server/`
  - splitting files formerly separated by this `STANDALONE` macro
  - also splitting functions some times
    - two functions instead of one: one for the server one client
    - and other refactoring will probably needed

This is a rather big issue, so it could be done in multiple steps.

**Comment by IAmNotHanni** [comment]
We're talking about refactoring only right? no enhancing.

**Comment by IAmNotHanni** [comment]
Ok I'm going to take care of this.

**Comment by IAmNotHanni** [comment]
Ok having started several times I think I now have a descrete plan how to refactor the game server code.
It has to be done step by step and this time I want to keep my commits stable.
Every class/struct/enumeration/macro will be moved into its own file.
This refactoring project also includes refactoring of the following files:

* fpsgame/game.hpp
* shared/tools.hpp
* fpsgame/ctf.hpp
* fpsgame/bomb.hpp
* fpsgame/collect.hpp
* fpsgame/capture.hpp
* fpsgame/hideandseek.hpp

TODO list:
* [ ] Move all enumerations into an own file in this folder: **inexor/enumerations/**
* [ ] Move all macros into an own file in this folder: **inexor/macros/**
* [ ] move all templates into an own file in this folder: **inexor/templates/**
* [ ] Replace all enumerations in **game.hpp** with their corresponding #includes
* [ ] Take apart **tools.hpp**: replace all definitions with #includes
* [ ] Take apart **fpsgame/server.cpp**
* [ ] Take apart **engine/server.cpp**

**Comment by IAmNotHanni** [comment]
I know that some don't like micro commits but I can squash them later anyways.
Also it is very easy to group together code parts once they are separated into all these files.

**Comment by Fohlen** [comment]
Refers to #70

**Comment by a-teammate** [comment]
This was done with #550
