### ISSUE TITLE
Get rid of the core repository and use media repositories as well.

### ISSUE THREAD

**Issue by Fohlen** [inexorgame/inexor-core#376]
As soon as possible I'd like to remove the `media` repository from `core` and pull it via the `media repository` feature introduced by @aschaeffer

**Comment by Croydon** [comment]
Do we not care about old Inexor versions not working anymore or do we somehow make sure to checkout some specific version of the media repositorys?

Note: This speeds up nightly packaging and uploading and saves space.

**Comment by Fohlen** [comment]
We could add a release tag for this as well. I wouldn't add "stability" as a priority for alpha releases though

**Comment by a-teammate** [comment]
already done in 4a09301bd2ab77b77cbf101927aa43752e77b2dd
