### ISSUE TITLE
Draft a media repository system

### ISSUE THREAD

**Issue by Fohlen** [inexorgame/inexor-core#378]
As we're finally getting at a technology point where we can use Node.js to build a media repository system, we should agree on a standard procedure for doing those things.

Below is a bit of collection of what's currently in mind:

- https://hackmd.io/EwUwhgnAJgbADFAtAVmQZiQFjgYwogDh2B0QHYwQDkqIxhkCg===#
- https://piratenpad.de/p/inexor-media-json
- http://www.sonatype.org/nexus/2017/02/14/using-nexus-3-as-your-repository-part-2-npm-packages/

As well @aschaeffer should give some feedback here, since he's currently the main drive behind the repository feature.

**Comment by aschaeffer** [comment]
This is working already
