### ISSUE TITLE
Schedule an Inexor meeting

### ISSUE THREAD

**Issue by Fohlen** [inexorgame/inexor-core#384]
I do see that we have quiet a lot of activity right now, which is why I'd like to suggest that we schedule the first Inexor meeting for this year.
Possible topics could be:

- introduce state-of-the art to everybody
- the new website
- Hackathon
- (...)

Best would of course be to open up a pad for this!

**Comment by a-teammate** [comment]
Could you create a pad?
https://hackmd.io/GwE2FYBYAYHYCYC0BOAps6jIksRBDZZSFfaAM3wCMBjDZfcoA===

**Comment by Croydon** [comment]
This is basically done by communication through all possible channels and/or at least thanks to your recent Hackathon. 😄
