### ISSUE TITLE
Inexor Flex connectors should use the LogManager for getting a logger

### ISSUE THREAD

**Issue by aschaeffer** [inexorgame/inexor-core#409]
### Goal

* Make logging in Inexor Core configurable using the same log configuration (logging.toml)

### Tasks

- [x] Use the LogManager for creating a logger for a Inexor Core instance
- [x] Extend logging.toml for some loggers of Inexor Core

**Comment by Fohlen** [comment]
actually we can write an anonymous function that will automatically set up when required.
This way we could refactor the `logger = logger()` syntax from existing modules

**Comment by aschaeffer** [comment]
https://github.com/inexorgame/inexor-flex/commit/9b6264dad99e5a21c710ae2b9c20d06eb97e1f2f
