### ISSUE TITLE
find a new structure to bundle InexorFlex and InexorCore

### ISSUE THREAD

**Issue by a-teammate** [inexorgame/inexor-core#419]
This is issue is about the file structure or the way to glue InexorFlex and InexorCore back together to one application.

This is an extended issue of #37

**Comment by aschaeffer** [comment]
| Audience | Target bundle format |
| ---- | ----|
| Developers | git submodules | 
| Linux-Users | deb/rpm/snap/flatpack/... Package |
| Windows-Users | Installer |

The file structure of the target bundle formats is different. In fact we need scripts to create a package or an installer automatically. This could be triggered by a new github tag.

**Comment by Fohlen** [comment]
For now the structure (for the release will be as following)

- inexor-core is released as bundle to GitHub
- inexor-flex is ordinarily releases to npm
- inexor-flex downloads inexor-core

This currently involves having npm installed, see #364 
Which could be deprecated by installers / packages in the future. Closing this for now

**Comment by a-teammate** [comment]
No, that would only work sanely for people using the prebuilt package from GitHub.

I would prefer a setup which is aimed towards developers in the file-structure.
Meaning: looks as closely as possible like a monolithic package
e.g.
--- inexor
-------- inexor-core
-------------- bin
-------------- src ...
-------- inexor-flex
-------------- config
-------------- interfaces
-------------- src

Is this somehow possible?

**Comment by Fohlen** [comment]
@a-teammate the structure would look like

--- inexor
------ inexor-core
--------- bin
--------- src
------ inexor-flex
--------- src
--------- server
--------- bin 
------ %APPDATA% or custom paths
--------- interfaces
--------- config
--------- media
--------- releases

you can configure all of the custom paths (which are determined by XDG standard paths) via NODE_ENV variables currently. We can ship a default `.nodenv` file for development, as we like

**Comment by a-teammate** [comment]
so you have `APPDATA/releases` and `inexor/inexor-core`?
or was that a typo?

**Comment by Fohlen** [comment]
`APPDATA/releases` is where the bundles from GitHub land. `inexor-core` is your git clone of `inexor-core` ?

**Comment by a-teammate** [comment]
Why make them different folders if they're actually containing the same?

**Comment by aschaeffer** [comment]
I think this ticket is (almost) resolved:

* Inexor Flex and Inexor Core are loosely coupled:
  * Inexor Core doesn't contain Inexor Flex anymore (no submodule)
  * Inexor Flex finds and/or installs Inexor Core instance(s) automatically

* A developer would make an link from the local development folder of Inexor Core to the releases folder and can use the local builds during development.

If we can close this issue, please change the milestone to 0.9.0-alpha first.

**Comment by Fohlen** [comment]
The architecture for this has been provided and implemented and is already live for `^0.9.0-preview`. Closing the ticket.
