### ISSUE TITLE
Update SDL to 2.0.8 when available + SDL_image 2.0.3

### ISSUE THREAD

**Issue by Croydon** [inexorgame/inexor-core#425]
So we get this patch: https://hg.libsdl.org/SDL/rev/3034ea08d805

@Fohlen did run into problems because of this bug.

**Comment by a-teammate** [comment]
the release we are waiting for is 2.0.6+

**Comment by Croydon** [comment]
https://www.libsdl.org/download-2.0.php

Available now.

**Comment by Croydon** [comment]
Many people from Sauerbraten&Tesseract have crashed with SDL 2.0.6 because of audio files. Maybe we should wait a bit longer.

**Comment by a-teammate** [comment]
we have audio disabled atm :) but good to know

**Comment by Croydon** [comment]
I just realized that seconds ago 😄 

However, there seems to be more problems then that. Seems to be an unmature release.

**Comment by Croydon** [comment]
SDL 2.0.7 available now.

**Comment by Croydon** [comment]
https://websvn.tuxfamily.org/comp.php?repname=tesseract%2Fmain&compare[]=/@2151&compare[]=/@2152

**Comment by Croydon** [comment]
https://github.com/bincrafters/conan-sdl2/pull/2
https://github.com/bincrafters/community/issues/203
https://github.com/inexorgame/inexor-core/commit/c9301d22c14bfe14c4dbcf4fc76f475b7437d0bc

**Comment by Croydon** [comment]
Done by #595

https://github.com/inexorgame/inexor-core/pull/595/commits/c9301d22c14bfe14c4dbcf4fc76f475b7437d0bc

https://github.com/inexorgame/inexor-core/pull/595/commits/e77766e1be1461e67ab22fb14ed6f7995d44b72f
