### ISSUE TITLE
Migrate init.cfg to TOML

### ISSUE THREAD

**Issue by aschaeffer** [inexorgame/inexor-core#427]
follow-up #368

### Tasks

- [ ] Remove init.cfg, writeinitcfg and loadinitcfg
- [ ] Create a new SharedVar (string) for the state of the instance

### Valid instance states

* stopped
* started (process is started, but not connected)
* running (process started, flex is connected)
* paused

**Comment by Fohlen** [comment]
This becomes obsolete as `cubescript` will not be supported any longer by the new engine.
