### ISSUE TITLE
Rename executable and proto files

### ISSUE THREAD

**Issue by aschaeffer** [inexorgame/inexor-core#430]
In order to improve the automatic startup of Inexor Core instances I would suggest to rename the resulting binaries and proto files according to this schema:

| Filename schema | Example | Description |
| --- | --- | --- |
| `inexor-core-{type}.exe`<sup>1</sup> | `inexor-core-server.exe` | The executable<sup>2</sup> |
| `inexor-core-{type}.proto`<sup>3, 4</sup> | `inexor-core-server.proto` | The protobuf descriptor file |

1. Lowercase filenames are more portable
2. On linux it's unusual to use the `.exe` file extension but it's not forbidden. But as regular users doesn't start the executable by himself it's better to have the same filename.
3. The same base name for the executable and the proto file
4. Use the same filenames for all platforms

| Type | Description |
| --- | --- |
| client | The game client |
| server | The game server |
| bot | (Optional) A bot |
| ... | _more types are possible_ |

**Comment by Croydon** [comment]
Could this conflict with Wine setups which are trying to execute the .exe file as a Windows binary?

**Comment by aschaeffer** [comment]
Linux executables have an [ELF header](https://en.wikipedia.org/wiki/Executable_and_Linkable_Format) and can be identified as linux binary. Windows executables have an [PE header](https://en.wikipedia.org/wiki/Portable_Executable). I haven't tested it, but I suppose wine is checking this first.

**Comment by a-teammate** [comment]
naming the file "..client.exe" would also cut the amount of people trying to click on "inexor.exe"

**Comment by a-teammate** [comment]
https://www.howtogeek.com/192628/mime-types-explained-why-linux-and-mac-os-x-dont-need-file-extensions/ -> .exe is no problem for linux

**Comment by aschaeffer** [comment]
:+1:
