### ISSUE TITLE
Create a wiki page for server installations

### ISSUE THREAD

**Issue by aschaeffer** [inexorgame/inexor-core#443]
1. Install dependencies (Node, NPM)
2. Download Inexor Flex
3. Install Inexor Core Server (hopefully using Flex)
4. Configure the profile
5. Create server instances
6. Use process manager for Inexor Flex: [PM2](https://github.com/Unitech/pm2)

**Comment by Croydon** [comment]
https://github.com/inexorgame/inexor-core/wiki/How-to-host-a-server

**Comment by IceflowRE** [comment]
Is libsdl really needed for building the server?

**Comment by a-teammate** [comment]
Nope, the whole process is outdated.
However we will remove the listenserver,  which is already done in a branch. That needs some debugging and extensive testing before merge, though.
as soon as the grpc module stops bugging for me I'll test it more and merge it in master

**Comment by Croydon** [comment]
Fixed here: https://github.com/inexorgame/inexor-core/issues/194
