### ISSUE TITLE
Hackathon 2017

### ISSUE THREAD

**Issue by Fohlen** [inexorgame/inexor-core#453]
This is the official Hackathon 2017 ticket, which I will update timely as needed.

## Steps
- [x] Find a city in which to host: Tuebingen
   - [x] Find a place to stay: private place organised by Fohlen
- [x] Find a host: [FabLab Neckaralb](fablab-neckar-alb.org)
- [x] Settle dates
   - 6t to 8th of October
- [x] Announce via a blog post
- [x] Make press announcement
  - social media
  - maker, hackerspaces via mail or Twitter
  - on Riot ofc.
  - (any other effective way to spread about the Hackathon)

## The blog post
The blog post should include the following

- a call for papers
  - I'd like to have at least 1, at maximum 5 presentations (given the size of the event)
  - as in 2015, a presentation about Inexor would be lovely
  - talk/workshop about the used technology is also very much appreciated, especially `flex`
- the dates for the event
- the *"package"* price, the package should include
  - the ticket for `the-tent`
  - a group ticket / pro-rata for the Munich suburb  
  - _(optionally)_ a "Inexorable" T-Shirt

**Comment by Fohlen** [comment]
> a_teammate: as a sidenote I would suggest we make it really clear that we are happy for people to just strive by to get things explained without need to commit themselves to the project (thats one of the things I dislike about the word "Hackathon" btw -> I immediately think "nah too much work, don't wanna be there")

**Comment by Fohlen** [comment]
I have opened a fresh pad for this at https://hackmd.io/IYDg7MBsAM0GYFoCMBmApgEwQFm2MCAnJBgKwIDGFcSYIkwKGwATEA==

**Comment by Fohlen** [comment]
I imagine the schedule to be like this

- **Friday**
  - Meet at 5pm at Munich Central Station (5pm should be feasible for everyone?)
  - Drive to the tent
  - Meet&Greet at 6pm or 6:15, so everyone has time to set up his place
  - Cooking at 6:30 (we better decide that at the-tent itself, before it gets an outburst in a Github Ticket 🗡 )
  - Other enjoyable evening activities
- **Saturday**
  - Breakfast at 10am
  - Official opening at 11:45am at Virtual Identity
  - 12:00-12:15 Introduction to Inexor (talk? Who want's?)
  - 12:15-13:00 Meet & Greet, Inexor install-party
  - 13:00-14:00 Workshop on Inexor Flex (I strongly recommend this)
  - 14:00 ~ 14:30 or 15:00 Food. I've been told there is a kitchen at VI, but we can order pizza too
  - 15:00 ~ 18:30 "Open Hacking", whatever that means (do music, code, images, textures, maps, story ideas, tickets ...........)
  - 15:00 - 15:45 Administrative work (tickets, projects, votings...)
  - 18:30, open end, Grill & Chill
    - at Virtual Identity
    - at the-tent
    - at the Isar-Park, it's lovely
  - later, do what you have to do
- **Sunday**
  - 11am - 12am Place for additional workshops or talks
  - 12-am - 2pm Open Hacking (as above)
  - 2pm-2:30pm Closing ceremony at Virtual Identity
  - 3:30pm - 4pm Closing ceremony the-tent
  - later, get home safely

**Comment by aschaeffer** [comment]
:+1: for the schedule

- [x] @aschaeffer Workshop on Inexor Flex

**Comment by Fohlen** [comment]
Following are the points for the administrative part of the Hackathon

- release 0.9
- write a blog post to the release
- check all the tickets concerning the release
- define a "Definition of Done" for tickets
- talk about standards, and the server-list proposal
  - if we can find a consens, decide a karma ranking table for the new proposal

**Comment by a-teammate** [comment]
answer from the Freiburger CCC:

> hi a_teammate,
> 
> Sauerbraten #FTW
> 
> Terminlich haben wir am 3. Oktober Türöffnertag der Sendung mit der Maus.
> am 7.10 eine kleine Geburtstagsfeier und vom 28.10-01.11. die Small Hackerspace Convention.
> 
> Somit wäre Wochenende 15.-17. und 20.-22. frei.
> 
> Je nach dem könnt ihr euch aber auch einfach der Small Hackerspace Convention anschließen sofern ihr kein Problem mit etwas mehr Trubel habt.
> Sofern ihr wirklich "nur" um die 10 Leute  wäre die SHC schon guter Platz. Ihr fändet mit Sicherheit Testspieler.
> 
> Gebt Bescheid wie es euch passt  ich denke wir werden eine Lösung finden.
> 
> Habt ihr jemanden aus dem Raum Freiburg im Team? Wäre super mal vorher jemanden Face to Face zu sehen.
> 
> Gruß Tau

**Comment by Fohlen** [comment]
Let's set this as the new date, fix the location etc

**Comment by MartinMuzatko** [comment]
> Somit wäre Wochenende 15.-17. und 20.-22. frei.

Meaning that 15-17 is the only weekend they can offer to us? 20-22 would be Wednesday to Friday.

**Comment by a-teammate** [comment]
I answered Tau:

I think the date is pretty much settled on the SHC weekend (27-29. 10.).
Our current issue is the accommodation. maybe some "jugendherberge" (^= youth hostel) is giving us a discount.

**Comment by Fohlen** [comment]
Since there's not been so much activity recently, here comes my suggestion

- I can organize everything in Tuebingen
- we can stay either at the University (I have staff access to developer rooms)
- or at the FabLab https://www.fablab-neckar-alb.org/ (I was a member there so it'll be very likely we can get any date we want)
- we can stay here, http://www.jugendherberge.de/de-de/jugendherbergen/tuebingen113/portraet

Below is a Doodle in which (regardless of the city) please everybody should add his favourite weekend in October.

https://doodle.com/poll/yfm6qz9cmzrrm4v3

**Comment by Croydon** [comment]
What about Freiburg? I was assuming this was pretty much settled already

**Comment by Fohlen** [comment]
I wasn't quiet so sure about that. Anyhow my offer is not intended to block the Freiburg event. I just think it'll be most usefull to have an average statistic about what weekend is good in October, so that we can have a more specific look based on the date.

**Comment by Fohlen** [comment]
Since @aschaeffer will probably not be able to join us on the weekend, who else is in for a flex workshop? Should I do it? In case I do it, who else would give an introduction to Inexor?

**Comment by Fohlen** [comment]
The accomodation is private and probably will be http://tuebinger-lichtenstein.de/

**Comment by Fohlen** [comment]
How about we create a flyer that we can use, maybe @aschaeffer or @IAmNotHanni do think that this is possible?

@Croydon mentioned that some parts of the blog post are outdated. Can you fix these?

**Comment by Fohlen** [comment]
Since this seems all settled, I will close the ticket.
I will try to print T-Shirts on Wednesday, it will cost < 10 euros. Please let me know via PM or mail if you want one.

**Comment by MartinMuzatko** [comment]
https://inexor.org/post/2017/09-28-inexor-hackathon-2017
