### ISSUE TITLE
Add a standards repository

### ISSUE THREAD

**Issue by Fohlen** [inexorgame/inexor-core#461]
In the future it will be very helpful for us to have a standards-repository

- this will include how to handle authentication
- how to handle server lists
- how to handle media repositories and sign them
- (more stuff)

I think it will be very good to have a dedicated standard repository, so that

- proposals can be tracked after time
- someone using Inexor knows how "we" do it
- alternate standards can derive
- someone "not doing it our way" can point out comparison to the standard (making it easy to explain both semantical and technical changes)

**Comment by Croydon** [comment]
The wiki seems good enough to me?

**Comment by Fohlen** [comment]
I don't know. In the wiki

- we cannot PR proposals to a standard or discuss on them
- updating the proposal is slightly less obvious to all the people involved
- proposals can't be locked

**Comment by aschaeffer** [comment]
Maybe we should first begin with a user documentation a la https://readthedocs.org/

**Comment by Fohlen** [comment]
Will that mean that we convert our wiki into readthedocs or would you maintain a separate documentation?

**Comment by aschaeffer** [comment]
I would suggest to create a user documentation for these audiences: players, mappers and game server owners. Everything related to development would be in the wiki.

This would have multiple effects:

* Players, mappers and game server owners won't be confused about all the technical stuff
* The wiki would be much cleaner
* We can use a [github repo as storage](https://github.com/rtfd/readthedocs.org#quickstart-for-github-hosted-projects)
