### ISSUE TITLE
Fork off node-segfault-handler

### ISSUE THREAD

**Issue by Fohlen** [inexorgame/inexor-core#465]
Fork off node-segfault-handler and package with `node-pre-gyp` to work around #456 

To-Do:

- [x] Fork the repository and rename stuff
- [ ] Upload binaries to Bintray
  - [ ] Use AppVeyor for Windows 
  - [ ] Use a Docker Xenial container with Node.js via Travis for Xenial binaries
    - [x] Add a matrix for multiple node versions ~~and distros (Trusty)~~
  - [ ] If not too hard, also build OSX binaries (this will probably greatly reward in the future, as people then use our module, it's quiet popular among OSX, afaik)
- [ ] Merge open pull requests from upstream, if useful
- [ ] Merge @a-teammate fixes
- [x] Use `@inexorgame/segfault-handler` to replace `segfault-handler` in flex

**Comment by Fohlen** [comment]
@Croydon said he would like to do the Docker/Travis fiddling

I will attach the summary from Riot here,

- run `npm install && npm install node-gyp -g`
- run `node-gyp && cd build && make`
- there will be some binary blobs in `build/Release`, namely the `segfault-handler.node` that need to be uploaded to Bintray

Consider the naming scheme from https://github.com/mapbox/node-pre-gyp#package_name to upload binaries

**Comment by Croydon** [comment]
>  Add a matrix for multiple node versions and distros (Trusty), (optional)

@Fohlen Is the binary Node.js and OS version specific?

**Comment by Fohlen** [comment]
@Croydon unfortanly yes. For Ubuntu 12 and 14 it might not matter because of (for older dists) GCC4 / GCC5 (for newer dists). Anyhow compiling the dependencies needs to be done at least for every different Node.js version since extensions are `NODE_ABI` dependant

**Comment by a-teammate** [comment]
Although the segfault-handler is very useful in the case of errors we can leave it out for 0.9.
I will still provide my fixes and am hoping that @Croydon could upload the binaries for 0.10.

**Comment by Croydon** [comment]
I will soon make time to work on this (just to make that clear).

But I'm also pretty sure that this decision will hunt us in the future. Do we really want to maintain it permanentely, can we maintain it permanentely and is there really no alternative?

We are not the only ones who want to invest Node.js app crashes, what are all these projects doing?

**Comment by Croydon** [comment]
I set up Docker containers with Ubuntu Xenial with Node.js 6 (LTS) and Node.js 8.
It compiles successfully. https://travis-ci.org/inexorgame/node-segfault-handler/builds/283043535

@Fohlen Are you already familiar with node-pre-gyp and how to use it?

**Comment by Croydon** [comment]
@a-teammate Where can I find your fixes?

**Comment by Croydon** [comment]
On a second look it's rather insane to fork this off and maintaince it by ourselves. We should look for other solutions.

**Comment by a-teammate** [comment]
This is very true..

**Comment by Croydon** [comment]
There is a decision to move away from Node, therefore we don't need node-segfault-handler anymore and even if, we should definitely not maintain our own node segfault handler.
