### ISSUE TITLE
Design a logo for Inexor flex

### ISSUE THREAD

**Issue by IAmNotHanni** [inexorgame/inexor-core#467]
Inexor flex is a keyword that stands for NodeJS integration in Inexor.
We need a cool logo in corporate design.

**Comment by IAmNotHanni** [comment]
How about this one?
![Error: inexor flex logo (png) found!](https://raw.githubusercontent.com/inexorgame/artwork/4b52298d9df12cc865659216954d7175e9f63bc3/flex/flex_logo_v1_rendered.png)

Need feedback from @a-teammate  @Fohlen @aschaeffer @Croydon.

**Comment by a-teammate** [comment]
inexor flex is not more a brand than inexor core, imo btw

**Comment by Croydon** [comment]
Looks nice. What font did you use there?

**Comment by IAmNotHanni** [comment]
It's not a font I created this using geometric approximations in Inkscape.

**Comment by Croydon** [comment]
Can you add it to https://github.com/inexorgame/artwork/tree/master/logo please?
