### ISSUE TITLE
Design and implement a new entity system

### ISSUE THREAD

**Issue by IAmNotHanni** [inexorgame/inexor-core#469]
Inexor's old entity system from Cube2 is very static and limited.
The new entity system will be the foundation for

* the **visual scripting system**
* the **new particle system**
* the **new map model system**
* the **new map sound system**

@aschaeffer has already implemented an [entity](https://github.com/inexorgame/inexor-core/tree/cef%2Bipc%2Bentities%2Bbezier/src/engine/entity) (plus a new particle system built on top) but we've agreed that it needs to be redone in order to refactor it once again and to find the right balance between intelligent software design patterns and simplicity.

**Comment by Fohlen** [comment]
How about we label this architecture documentation rather than "demand analysis" 😆

**Comment by Croydon** [comment]
I'm not sure why we need another issue for that.

We already have #78 and #322 as major ones and also #334, #327, #335 and a few slightly related ones.
