### ISSUE TITLE
cross platform way to upgrade node.js and npm

### ISSUE THREAD

**Issue by a-teammate** [inexorgame/inexor-core#470]
As time shifts we will need to upgrade node.js and npm as @Croydon  already mentioned.  
So when striving for an automatic upgrading of inexor ( #37 ) we need to handle the case that flex requires a newer version of nodejs.

packages which might help: 
* https://github.com/coreybutler/nvm-windows
* https://github.com/creationix/nvm

Edit:
The problem is:
imagine we need a newer version of nodejs for a newer version of flex. how would we upgrade node?
we upgrade inexor-flex in the npm prestart section.
Now the new inexor-flex requires a new nodejs version. how do we upgrade?

**Comment by Croydon** [comment]
Before we speak about upgrading we should speak about installing them I guess :)

**Comment by aschaeffer** [comment]
Upgrading node.js and npm doesn't have any prio atm. The requirements for node.js and npm are set and won't change soon. I would suggest to remove it from milestone 0.9.0-alpha

**Comment by Fohlen** [comment]
@a-teammate just giving you a quick reminder about #452 where we agreed not to extend the release without prior agreement/discussion any more. Removing the milestone.

**Comment by a-teammate** [comment]
Actually this is not a new issue, this is just a part of #37 we already agreed on.
Nvm it's okay if that's not for 0.9
@Croydon true. we should speak about both in this issue, since in this case it's pretty much the same (upgrading and installing from scratch) as it requires the same tools. (Then we just let the from-scratch-installer wrap the method we choose here)

**Comment by Fohlen** [comment]
I've been thinking about this issue again. I think that, when we will install the LTS version of `node.js` it will be sufficient and serve an up-to-date, compatible version of `node` for at least 2 years. This is not a pressing issue. We can also think about using `flex` to initiate an update script (which the user will have to agree to). There are plenty of options.

**Comment by a-teammate** [comment]
**Note**:
After upgrading nodejs the native modules grpc and nodegit need to be upgraded!
`npm rebuild nodegit grpc --update-binary`

**Comment by Croydon** [comment]
> on windows i found out its very easy: just download the node installer and run it again. in passive mode, the user does not even need to interact :)

This could mess up the configuration if the user already has a different Node.js installed and we just either overwrite or install a second version, right? At least if we add it to the path. Are we doing that?

**Comment by a-teammate** [comment]
What kind of configuration?
The silent installer is not for devs, it's for players. Devs will have the option to skip an upgrade.
Otherwise this is the recommended kind to upgrade nodejs on windows: rerun the installer

**Comment by rv4Flyver** [comment]
Greetings!
I've noticed that game installer removes older nodejs version and replace it with v8.3 (at this particular moment) and found that very irritating since I need to work with v6.
Please, consider local nodejs installation as workaround for this as I'm sure that updating environment of the user (at least silently)  can be considered as a bad attitude.

**Comment by a-teammate** [comment]
Yeah sorry for that!
At this very moment working on a better solution :)

**Comment by a-teammate** [comment]
its fixed with the newly uploaded installer :)

**Comment by Croydon** [comment]
Closing as the decision was made to move away from Node.js
