### ISSUE TITLE
Unable to run inexor.bat file after following build Wiki instructions

### ISSUE THREAD

**Issue by bobbybrot** [inexorgame/inexor-core#480]
I have been brought to an issue where I am unable to execute _inexor.bat_ file after following the Windows installation instructions that can be found on the Wiki page of inexor_core.
I have also attempted to follow the tutorial closely and even use SmartGit instead of Github to get a copy of the files and store them locally on my PC, however this has lead to the same errors that are produced when firing up that bat file.
Below is an image of the Command Prompt output:
![image](https://user-images.githubusercontent.com/25210476/30080956-5b0be4b6-927d-11e7-93ae-1548f69898f7.png)

**Comment by a-teammate** [comment]
i made some edits to the wiki:
https://github.com/inexorgame/wiki-mirror/compare/df274ba3a829...9282b60b851c
does it work now?

**Comment by bobbybrot** [comment]
Hey @a-teammate, I am afraid it didn't work, I was given the following error when i did the 'npm install' command through both Git Bash and Powershell: 
![image](https://user-images.githubusercontent.com/25210476/30132128-3439755e-9347-11e7-8134-56931d6c4b3c.png)

**Comment by bobbybrot** [comment]
I followed the tutorial again noting this time I used Github Desktop Beta as I uninstalled SmartGit. I think I will redo the tutorial once more time through smartgit and reinstall all other dependencies such as conan and python.
