### ISSUE TITLE
conan-CEF errors if whitespace in username

### ISSUE THREAD

**Issue by a-teammate** [inexorgame/inexor-core#485]
Either this https://github.com/inexorgame/conan-CEF/blob/stable/3.2704.1424.gc3f0a5b/conanfile.py#L69
need to become `args = ['-DCEF_ROOT="{}"'.format(self.get_cef_distribution_name())]`
or that https://github.com/inexorgame/conan-CEF/blob/stable/3.2704.1424.gc3f0a5b/conanfile.py#L73
needs to become `self.run('cmake "{}" {} {}'.format(self.conanfile_directory, cmake.command_line, " ".join(args)))`

If we do both, the error probably goes away which appears if you try to `conan install CEF/3.2704.1424.gc3f0a5b@inexorgame/testing` with a user name with spaces (or somehow similar when building in a folder with spaces)

what to do?
- [x] reproduce the error
   * by either creating a new user with spaces in the name
   * or by finding a way to build a conan package in a different folder than `C:/users/user name/.conan/data` e.g. "D:/test folder/conan-cef"
- [x] add the two lines
- [x] build the new package (test the fix)

**Comment by Croydon** [comment]
https://github.com/inexorgame/conan-CEF/commit/d7e4076799c3fdb26dd1ce9a1543d94c46dcc665

**Comment by a-teammate** [comment]
(the second line was the problem: no `"` around self.conan_directory.
attention: could be an undiscovered issue for other conanfiles as well.)
