### ISSUE TITLE
When tagging a new version of inexor-core mention current flex-version/media-essential/media-additional

### ISSUE THREAD

**Issue by Croydon** [inexorgame/inexor-core#489]
When tagging a new version of inexor-core mention current flex-version/media-essential/media-additional  in tag description.

This should help to reproduce builds of Inexor 1:1.

**Comment by Croydon** [comment]
We have the same problem with the media repository.

**Comment by Fohlen** [comment]
https://stackoverflow.com/a/37805651/3135319

**Comment by a-teammate** [comment]
idk fohlen. the idea is to post it in the release description, so its easier applicable for users.

the ci would basically do:
- clone flex/media (with depth 1)
- checkout master
- get sha of head
- use that information when creating the tag description (is appveyor or travis doing it, i dont remember)

**Comment by Croydon** [comment]
Cloning isn't necessary, there is https://git-scm.com/docs/git-ls-remote

**Comment by Fohlen** [comment]
The best way of doing this is with submodules

- add a folder named refs or something
- add submodules for flex, essential, additional
- increase the submodule commit(s) on tagging
- add this to the release commit

=> voila. 100 percent reproducable. no need to spam the commit log.

**Comment by Croydon** [comment]
> => voila. 100 percent reproducable. no need to spam the commit log.

Actually it's your solution which would spam the commit log (by creating new commits).

My idea was simple mentioning the commit hashes in the tag description.
