### ISSUE TITLE
Make our Conan CEF package a clean self-contained package

### ISSUE THREAD

**Issue by Croydon** [inexorgame/inexor-core#490]
Currently, we need to install manually CEF dependencies, let's try to build this all clean.

Potentially looking into #371 when doing this.

**Comment by Croydon** [comment]
There is no need anymore to install the system requirements manually, this should be done via the recipe. 

It's an ongoing maintenance work to get this done for different package managers/linux distributions. Right now it supports Ubuntu (and theoretically Debian). It should be expanded on a per-request level. I will soon add Fedora support.

Beyond that I'm closing this in favour of https://github.com/conan-io/wishlist/issues/103

**Comment by Fohlen** [comment]
This is nice! However what's the status of `conan-cef`. Will we be able to include it into our build?

**Comment by Croydon** [comment]
`conan-cef` is part of our build for 2 years now

https://github.com/inexorgame/inexor-core/commit/774960689f3dba20e77f2c4913788f5623dce0ca#diff-813e9359602d91235f3a3a9512bc50d6
