### ISSUE TITLE
nodegit can't get compiled with Python 3

### ISSUE THREAD

**Issue by Croydon** [inexorgame/inexor-core#492]
Check if we can do this?

**Comment by Fohlen** [comment]
Is this certain? :octocat:

**Comment by Croydon** [comment]
nodegit requires gyp, which doesn't support Python 3, so this is a problem for all Node.js versions which doesn't have binaries for easy download.

This will become better when nodegit adopts n-api. Till then I will try to make a pull request for each new major Node.js version to the nodegit repo to keep their CI building up-to-date.

**Comment by Croydon** [comment]
Python 2 will be soon deprecated and end of life 2020.
So Node.js definitely needs to move sooner or later or add Python 3 support.

**Comment by Croydon** [comment]
Closing this in flavor of #609.

Also we can't do much here anyway when we stay with nodegit.
