### ISSUE TITLE
Hackathon 2018 Ⅰ

### ISSUE THREAD

**Issue by Croydon** [inexorgame/inexor-core#497]
# We have a date and a location:
https://github.com/inexorgame/inexor-core/issues/497#issuecomment-370255377
____

We recently had our Hackathon 2017.
Since our first Hackathon was at the end of 2015, we almost let two years go by till we meet again.
It was pretty much common sense among us that we want to have more **regularly Hackathons - at least once yearly**.

Also, we spoke a bit about possible next dates and locations.

**Late February - end of March 2018** seems to be a good time span for trying to find an exact date.

Moreover, good chances for the location seems to be (which is not exclusive and we have almost endless other options, so  we might end up somewhere which is not listed here):
 * Darmstadt, Germany (@Croydon & @aschaeffer could manage this)
 * Mainz, Germany (@IAmNotHanni might be able to manage this)
 * Freiburg, Germany (@a-teammate got positive feedback from the CCC there)
 * ~~Salzburg, Austria (@koppiman said he could manage this)~~
 * once again Stuttgart (like 2015) or Tuebingen (like 2017) (@Fohlen & @a-teammate could likely manage this)
   * contra: chance to attract new people/making connections is huger if we move around and don't fix on a single location/narrow district 

I suggest that we start planning this in detail in early December, till then we could loosely collect possible opportunities. // @inexorgame/code-developers  @inexorgame/content-folks

**Comment by a-teammate** [comment]
as I said, the Freiburger CCC already replied with a positive answer.
They are playing with the idea to move into bigger rooms in spring, so the accommodation problem could be fixed (if they find a proper location).

**Comment by koppiman** [comment]
Hackathon is possible in Salzburg at 23th to 25th of March.
I recommend confirmation to participation via telegram by typing "i will participate", cause I do look more for telegram than github.
Destination would be: https://www.kolpinghaus-salzburg.at/
Rooms are 4 persons each room 106 € per night
I would have to confirm order this week so please send confirmation as told above.

**Comment by koppiman** [comment]
PS.: I am still working on a cheaper solution, but not sure if it will work.

**Comment by koppiman** [comment]
Also cheaper means no parking possibilities for cars.
Sry for that

**Comment by Croydon** [comment]
**Please add yourself here if you are interested in our Hackathon:** 

https://cloud.noobys.org/apps/polls/poll/4vvB0Xf81Lr3is2K

**Comment by Croydon** [comment]
Salzburg won't happen. Let's search again.

**Comment by Croydon** [comment]
Back to the basics:

Who is interested in participating in our Hackathon?
Who has time when?

We will try to figure out a location in the meantime. It will be somewhere in Germany or not to far away.

Please add yourself: https://cloud.noobys.org/apps/polls/poll/MtnxNJgBrnkwyhXo

**Comment by a-teammate** [comment]
@Croydon

Could we reschedule it to take place a month or two later?
Last time it fell on our foods that we needed two change everything in short time. It was still a nice hackathon, but i think if we take more time everyone can prepare better. Including booking tickets and telling you company you are not available at these dates.

**Comment by Fohlen** [comment]
I agree to @a-teammate 
Maybe for the future can we guideline such a process so that it will work out more gently?
We could maybe add Doodle to our website, or similar things.

I can also offer to do the Hackathon at the Fablab/Tübingen again, as far as I can see also with free accommodation, like the last time 👍

**Comment by MartinMuzatko** [comment]
Hello. As announced in the Telegram chat, I am currently moving with my partner to a house in [Warmbronn](https://www.google.com/maps?hl=en&q=warmbronn).
We have at least 120m² of space available there on 3 floors and we could offer beds for up to 12 people and space for a lot more. When we are done moving (approx april/may) we would very much love to host the Inexor Hackathon. Please let me know if this is an option for you. Since we both love to cook, we would also take care about catering as long as everybody chips in and shares the food cost. Alternatively, we can still get some food delivered here. We are trying to generally create a hackerspace atmosphere, as we are doing a lot of home automation with custom switches, Raspberry/nodejs controlled LED strips, etc. Once we are somewhat close to done, I'd love to post some pictures.

**Comment by aschaeffer** [comment]
https://doodle.com/poll/4hxh67hsu74c73yy

**Comment by Croydon** [comment]
> https://doodle.com/poll/4hxh67hsu74c73yy

What kind of location will this be?

**Comment by a-teammate** [comment]
See the meeting protocol https://hackmd.io/EYRgDAJgLAzAnDAtAQwBxioqIDGZGrz5QDsAZgGzAZjJioCsQA==#

**Comment by Croydon** [comment]
It's just says max 10 people and free sleeping spaces.

Is it a private place? Public place? Will it be a public hackathon?

**Comment by aschaeffer** [comment]
Date and location are settled:

* ```13. - 15. April 2018```

* Kopernikuspl. 2, 88131 Lindau, Germany
* https://www.google.de/maps/place/Kopernikuspl.+2,+88131+Lindau+(Bodensee)/@47.5416936,9.732196,17z/data=!3m1!4b1!4m5!3m4!1s0x479b0d07228475a1:0x716d310a3f533233!8m2!3d47.54169!4d9.73439

**Comment by Croydon** [comment]
This still needs a public announcement in form of a blog post and social media posts.

Also please provide start and ending times for each day.

**Comment by a-teammate** [comment]
I would say we should publish it today evening (or simply ASAP). Should we send the link of the blogpost to CCC mailing lists in the area as well? (e.g. the ccc markdorf)

I don't know whether I can do it today evening, maybe someone else could help out for that? :)

**Comment by Croydon** [comment]
Someone needs to approve the pull request.

**Comment by Croydon** [comment]
Successfully took place :)
