### ISSUE TITLE
Overall feature roadmap for Inexor

### ISSUE THREAD

**Issue by Fohlen** [inexorgame/inexor-core#514]
Since I've been missing this for a couple of times, and everyone has a separate opinion on this one, here it is, the "overall roadmap for Inexor" ticket.

So, after the rolling release, 0.9, what's there to come?
_Note:_ The list is ordered by two indicators: how much the ticket is needed, and how likely it is for someone to implement (e.g, boring tasks are less likely). Mandatory issues are **bold**.

## Core

- **make list and object types synchronisable via RPC** @a-teammate 
- **fix a lot of CEF stuff** @aschaeffer 
- **get OSX running** @Fohlen @Croydon 
- **`refactoring`** 
- **implement the new entity system** @aschaeffer @IAmNotHanni 
- **implement dynamic game modes** @Fohlen
- implement step sounds
- implement bezier curves
- implement map version control
- implement bgfx as renderer, see #160 and #477 

## Flex

- **implement a server network** @Fohlen, @aschaeffer 
- **add a "package repository network"** @aschaeffer 
- **add a scripting system** @Fohlen
- add authentication features (certificate, OAuth)
- add more fancy default features (e.g mapvote ..)

## Media

- **deprecate all cubescript things**
- make our "core content" work 

## UI

- **add a complete UI rewrite of the old cubescript stuff**
- **add a cool, movable and leightweight HUD and default HUD**
- **add a new fancy console, deprecate the old /t based console** 

## Website

- add more community features, e.g #263 

Please add what you think is missing or incorrect. Also. If you like, add your name if you're interested.

**Comment by Croydon** [comment]
I don't like this issue. If we start discuss here specific features we will just split the discussions over even more places. Let's just discuss each feature's urgency, planning and details in the respective single issue please?

Also we have milestones, which indicates what features we want to have till when. For "until the frist stable version": https://github.com/inexorgame/inexor-core/milestone/13
We can discuss if we want to have it at last till 1.0 in the respective issue, then add/remove it to the milestone. If it is added to a milestone prior to 1.0 then we also want to have it obviously.

Also we have this mysterious label "prio:RELEASE", which has to mean something, even though, nobody ever could explain it to me and I asked several times at several places.

**Comment by Fohlen** [comment]
@Croydon this is not a definite, we must do it, or must discuss it this way. We could also likely move this to a pad. It's just a very good overview of what's on the list..

**Comment by MartinMuzatko** [comment]
In my experience, roadmap issues in other repos worked pretty well to discuss the ongoing features that are wanted to be seen and to give an overview of what has been done, other than checking closed issues.
You should link to individual issues if possible.

**Comment by Fohlen** [comment]
@a-teammate @aschaeffer @IAmNotHanni westernheld + Karpador discussed this in the channel today and it still seems very much relevant for our team! We should discuss this on the next Hackathon!

**Comment by a-teammate** [comment]
This can probably be closed, as we are investigating better ways to do this, see #558
I suggest we open a new issue for specifying how to organize sprints, issues, people .. see #558 again.

**Comment by Croydon** [comment]
> a very good overview of what's on the list..

Milestones.

> It also helps to establish something like a changelog before the release.

Milestones, also commits. We changed our commit style for this single reason.

> give an overview of what has been done

Milestones, also changelog, also commits from tag ranges.


If this still needs further discussion -> #558.
