### ISSUE TITLE
Nodegit compiles only for very few configurations

### ISSUE THREAD

**Issue by Fohlen** [inexorgame/inexor-core#515]
Nodegit currently only compiles for https://github.com/nodegit/nodegit/blob/master/.travis.yml
This is bad because

- Xenial is not targeted via dist (Wily is default on Travis)
- ~~The wrong Node versions (not 6, 7, 8 stable but some weird stuff) are targeted~~
- This ofc does also break compiling for us..

Maybe we can do a PR at their repo including
- a Matrix with Docker to add Xenial and Zesty
- to add the latest and/or more node.js versions

**Edit (Croydon): Node.js 6, 7 and 8 are targeted now**

**Comment by MartinMuzatko** [comment]
Maybe I do not understand Docker correctly, but can't we use docker to make the software that depends on nodegit run in an environment where nodegit installs?

**Comment by Croydon** [comment]
This would required to run flex completely within Docker which adds a complexity which isn't justified for this problem.

The are targetting now Node.js 6, 7 and 8 https://github.com/nodegit/nodegit/commit/b9831415618b84e25ed053a86bbadcd5ae86da78

**Comment by a-teammate** [comment]
The problem is that nodegit is a native c module
The Bindings for native node modules are not ABI stable, which means that with every new version of node, the native module needs to be recompiled. even for minor versions

**Comment by Croydon** [comment]
https://github.com/nodegit/nodegit/pull/1444

**Comment by Croydon** [comment]
Done with:
  * https://github.com/nodegit/nodegit/pull/1444
  * https://github.com/inexorgame/inexor-flex/commit/fd36fbded22cc861f963bc275e273cec3c57d4db
  * https://github.com/nodegit/nodegit/pull/1447

at least for now. This will be an ongoing effort.

Building for different Ubuntu versions shouldn't be required as the (ABI) compatibility should depend only on nodegit/nan/Node.js.

**Comment by Croydon** [comment]
> (Wily is default on Travis)

@Fohlen FYI, with some Travis configurations you still get Ubuntu Precise (12.04) as default, in most configurations you are getting Ubunu Trusty (14.04) right now. Wily is not available.
