### ISSUE TITLE
Flex doesn't start successfully, module node-rest-client missing

### ISSUE THREAD

**Issue by FraMecca** [inexorgame/inexor-core#516]
Hi all, 
Inexor seems very interesting for an old sauerbraten player, from a design point of view.

My current issue is that I can't play it. I tried:

1. Build from source. The version of boos conan links to is different from the one installed on my laptop so at runtime the program segfaults. Also, why do I have to recompile the whole boost if I compile from source? The current conan processo should pick system installed libraries first.

2. I downloaded the release archive. When I tried to execute bin/inexor-core-client.exe I got:

```
07:36:58 [global] [info] Driver: 3.0 Mesa 17.0.7
07:36:58 [global] [warning] could not load texture texture/inexor/notexture.png
07:36:58 [global] [critical] could not find core textures
fish: “./inexor-core-client.exe” terminated by signal SIGSEGV (Address boundary error)
```

3. Tried to clone to repo and run bash script:
It fails because the fles subdir is not installed and .gitsubmodules is empty. Even if I clone the flex submodule in the folder I get:

```
> @inexorgame/inexor-flex@0.9.0-preview20 start /home/user/Downloads/inexor-core-0.8.13@latest-Linux64/inexor-core/flex
> node server/index.js --profile  $npm_package_config_profile

/home/user/Downloads/inexor-core-0.8.13@latest-Linux64/inexor-core/flex/server/index.js:8
let flexArgs = new FlexArgs();
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
```

**Comment by Fohlen** [comment]
Hello @FraMecca 
This is due to running an older, unsupported version of Node.js.
Actually this should not even be possible (thanks npm!) and throw a warning.
Depending on your Node.js version however, this might work in harmony mode.

Can you try `node inexor.js --harmony` ?
If this won't work for you, please consider to upgrade to `node=7.3.0` (it's the version we know of supported to work)

Please keep us updated wether that works for you! We'd like to get the rolling release system as bug-free as possible 👍

**Comment by a-teammate** [comment]
Hey there @FraMecca 
1.
I don't really know why it fails for you, but may it be that its the same error as 2.? missing core textures?
If not there is an error in the build pipeline.
If the error is that it tries to resolve a different boost version at runtime, we should investigate whats wrong with the rpath. But actually boost should get linked statically.. so dunno.
We should **never** require any system libraries to be installed (there are open bugs that CEF needs some packages and that SDL2 needs some for building) for the reasons that:
* We want reproducible builds
   * so we know exactly the setup of all devs (when one has a lot of dependencies its some effort to always ask: which version of x do you got installed, which of y? followed by trying to reproduce it)
   * even if that means some longer times to setup the environment
      * i.e. building or downloading boost
      * Usually there are cached packages for most compilers and most of our dependencies
      (except some we excluded on purpose).
        What is your compiler version and arch?
* We gain self-contained packages
     * when we build everything from source and only build static packages, the packages are highly portable. As soon as we link anything statically we could drop the linux binaries on any unix compliant OS we want, it should just work. (Windows works this way anyways, Linux is trying to adapt to it with stuff like snapcraft and docker)

2.
Yeah, the inexor-core binary is helpless at its own. it needs inexorflex to start it and feed it with startup parameters and configs.
maybe you could try https://github.com/inexorgame/inexor-core/wiki/Run-Inexor (this page is pretty new, please ask for any unclear or incorrect passages):
- install nvm
- install node 8.3.0 via nvm
- do `npm install --global @inexorgame/inexor-flex`
- start inexor via the terminal `inexor-flex` (should need some time at first start)

3.
Ups yeah, we should remove the bash scripts! I forgot that for the master branch.
they are not the way to go currently. anything startup related should actually be at inexor-flex side

----
@Fohlen: https://github.com/inexorgame/inexor-flex/blob/master/package.json#L36
it seems the engine field is not up to date.

**Comment by Fohlen** [comment]
You're right @a-teammate

**Comment by a-teammate** [comment]
any update?

**Comment by Croydon** [comment]
@FraMecca Could you please re-try with a fresh setup? A lot did change since you first tried.

**Comment by FraMecca** [comment]
this is what I get
https://ghostbin.com/paste/cq856

Basically I can build
run inoxer-flex
and wait countless for:
    Feb 11 07:06:49 flex.server.ProcessManager[21211] INFO:  Inexor Flex process exited with exit code 0
Feb 11 07:06:51 @inexorgame/flex[21169] ERROR: Inexor Flex didn't came up:
Feb 11 07:06:51 @inexorgame/flex[21169] ERROR: Timeout
  err: Error: Timeout
      at Timeout._onTimeout (/snap/inexor-flex/x2/lib/node_modules/@inexorgame/inexor-flex/node_modules/wait-on/lib/wait-on.js:91:10)
      at ontimeout (timers.js:386:14)
      at tryOnTimeout (timers.js:250:5)
      at Timer.listOnTimeout (timers.js:214:5)

**Comment by Croydon** [comment]
inexorgame/inexor-flex@0.9.0-alpha isn't up to date

**Comment by FraMecca** [comment]
this is what I get now

``user ~/i/inexor-core (master)> /home/user/node_modules/.bin/inexor-flex 
Feb 11 19:58:13 @inexorgame/flex[10038] WARN:  Inexor Flex is not running! Starting Inexor Flex...

> @inexorgame/inexor-flex@0.9.3 start /home/user/node_modules/@inexorgame/inexor-flex
> node server/index.js --profile  $npm_package_config_profile

Feb 11 19:58:15 flex.profiles.ProfileManager[10060] INFO:  Loading profiles from /home/user/node_modules/@inexorgame/inexor-flex/config/profiles.toml
Feb 11 19:58:15 flex.profiles.ProfileManager[10060] INFO:  Using profile client
Feb 11 19:58:15 flex.logging.LogManager[10060] INFO:  Loading logging configuration from /home/user/node_modules/@inexorgame/inexor-flex/config/client/logging.toml
Feb 11 19:58:16 flex.media.repository.FilesystemRepositoryManager[10060] INFO:  Added FS media repository user: /home/user/.local/share/inexor/media/user
Feb 11 19:58:16 flex.media.repository.GitRepositoryManager[10060] INFO:  Added GIT media repository additional: /home/user/.local/share/inexor/media/additional
Feb 11 19:58:16 flex.media.repository.GitRepositoryManager[10060] INFO:  Added GIT media repository essential: /home/user/.local/share/inexor/media/essential
Feb 11 19:58:16 flex.interfaces.WebUserInterfaceManager[10060] INFO:  Loading interfaces from /home/user/node_modules/@inexorgame/inexor-flex/config/client/interfaces.toml
Feb 11 19:58:16 flex.releases.ReleaseManager[10060] INFO:  Loading release config from /home/user/node_modules/@inexorgame/inexor-flex/config/releases.toml
Feb 11 19:58:16 flex.server.FlexServer[10060] INFO:  Inexor Flex is listening on http://localhost:31416
Feb 11 19:58:16 flex.server.FlexServer[10060] INFO:  Essential and additional ready
Feb 11 19:58:16 flex.instances.InstanceManager[10060] INFO:  Loading instances from /home/user/node_modules/@inexorgame/inexor-flex/config/client/instances.toml
Feb 11 19:58:16 flex.interfaces.WebUserInterfaceManager[10060] INFO:  Updating interface at /home/user/.local/share/inexor/interfaces/console
Feb 11 19:58:16 flex.interfaces.WebUserInterfaceManager[10060] INFO:  Updating interface at /home/user/.local/share/inexor/interfaces/hud
Feb 11 19:58:16 flex.interfaces.WebUserInterfaceManager[10060] INFO:  Updating interface at /home/user/.local/share/inexor/interfaces/client-interface
Feb 11 19:58:16 flex.interfaces.WebUserInterfaceManager[10060] INFO:  Updating interface at /home/user/.local/share/inexor/interfaces/ui-flex
Feb 11 19:58:16 flex.releases.ReleaseManager[10060] INFO:  
  releases: {"explicit_release_folders":[],"download_destination_provider":"local_cache","provider":[{"name":"local_cache","type":"filesystem","path":"releases"},{"name":...
Feb 11 19:58:16 flex.releases.ReleaseManager[10060] INFO:  Using the provider local_cache as cache folder (/home/user/.local/share/inexor/releases)
Feb 11 19:58:16 flex.releases.ReleaseManager[10060] INFO:  Checking for new releases
Feb 11 19:58:16 flex.releases.ReleaseManager[10060] INFO:  Scanning folder /home/user/.local/share/inexor/releases for downloaded releases
Feb 11 19:58:16 flex.releases.ReleaseManager[10060] INFO:  Fetching latest releases from  https://api.github.com/repos/inexorgame/inexor-core/releases
/home/user/node_modules/rx/dist/rx.js:77
    throw e;
    ^

Error: Cannot find module 'node-rest-client'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/user/node_modules/@inexorgame/treeclient/TreeClient.js:1:78)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
Feb 11 19:58:16 flex.media.repository.GitRepositoryManager[10060] ERROR: [additional] Failed to get current branch: reference 'refs/heads/master' not found. The repository additional seems to be corrupt
(1) user ~/i/inexor-core (master)> Feb 11 19:58:16 flex.instances.InstanceManager[10060] INFO:  Starting instance Default production client (id: 31417, type: client, port: 31417)
Feb 11 19:58:16 flex.releases.ReleaseManager[10060] INFO:  Checking for new releases
Feb 11 19:58:16 flex.releases.ReleaseManager[10060] INFO:  Scanning folder /home/user/.local/share/inexor/releases for downloaded releases
Feb 11 19:58:16 flex.releases.ReleaseManager[10060] INFO:  Fetching latest releases from  https://api.github.com/repos/inexorgame/inexor-core/releases
Feb 11 19:58:16 flex.media.repository.GitRepositoryManager[10060] ERROR: [essential] Failed to get current branch: reference 'refs/heads/master' not found. The repository essential seems to be corrupt
Feb 11 19:58:17 flex.interfaces.WebUserInterfaceManager[10060] INFO:  [Inexor Web Interface] Checked out latest master
Feb 11 19:58:17 flex.interfaces.WebUserInterfaceManager[10060] INFO:  Enabled user interface /home/user/.local/share/inexor/interfaces/client-interface/dist on /api/v1/interfaces/client-interface/
Feb 11 19:58:17 flex.interfaces.WebUserInterfaceManager[10060] INFO:  [Inexor Web Console] Checked out latest master
Feb 11 19:58:17 flex.interfaces.WebUserInterfaceManager[10060] INFO:  Enabled user interface /home/user/.local/share/inexor/interfaces/console/dist on /api/v1/interfaces/console/
Feb 11 19:58:18 flex.releases.ReleaseManager[10060] INFO:  A release with version 0.9.7 in channel 'alpha' has been added (provider: inexor_github)
Feb 11 19:58:18 flex.releases.ReleaseManager[10060] INFO:  A release with version 0.9.6 in channel 'alpha' has been added (provider: inexor_github)
Feb 11 19:58:18 flex.releases.ReleaseManager[10060] INFO:  A release with version 0.9.2 in channel 'alpha' has been added (provider: inexor_github)
Feb 11 19:58:18 flex.releases.ReleaseManager[10060] INFO:  A release with version 0.9.1 in channel 'alpha' has been added (provider: inexor_github)
Feb 11 19:58:18 flex.releases.ReleaseManager[10060] INFO:  A release with version 0.9.0 in channel 'alpha' has been added (provider: inexor_github)
Feb 11 19:58:18 flex.releases.ReleaseManager[10060] INFO:  A release with version 0.8.14 in channel 'alpha' has been added (provider: inexor_github)
Feb 11 19:58:18 flex.releases.ReleaseManager[10060] INFO:  A release with version 0.8.13 in channel 'alpha' has been added (provider: inexor_github)
Feb 11 19:58:18 flex.releases.ReleaseManager[10060] INFO:  A release with version 0.8.12 in channel 'alpha' has been added (provider: inexor_github)
Feb 11 19:58:18 flex.releases.ReleaseManager[10060] INFO:  A release with version 0.8.11 in channel 'alpha' has been added (provider: inexor_github)
Feb 11 19:58:18 flex.releases.ReleaseManager[10060] INFO:  Found a release which is available, but not yet installed: 0.9.7@alpha ! Downloading and installing automatically...
Feb 11 19:58:19 flex.interfaces.WebUserInterfaceManager[10060] INFO:  [Inexor Client HUD] Checked out latest master
Feb 11 19:58:19 flex.interfaces.WebUserInterfaceManager[10060] INFO:  Enabled user interface /home/user/.local/share/inexor/interfaces/hud/dist on /api/v1/interfaces/hud/
Feb 11 19:58:21 flex.interfaces.WebUserInterfaceManager[10060] INFO:  [The Flex user interface] Checked out latest master
Feb 11 19:58:21 flex.interfaces.WebUserInterfaceManager[10060] INFO:  Enabled user interface /home/user/.local/share/inexor/interfaces/ui-flex/dist on /api/v1/interfaces/ui-flex/
Feb 11 19:58:44 flex.releases.ReleaseManager[10060] INFO:  /home/user/.local/share/inexor/releases/inexor-core-0.9.7@alpha-Linux64.zip
Feb 11 19:58:44 flex.releases.ReleaseManager[10060] INFO:  55938569
Feb 11 19:58:44 flex.releases.ReleaseManager[10060] INFO:  Release with version 0.9.7@alpha has been downloaded to /home/user/.local/share/inexor/releases/inexor-core-0.9.7@alpha-Linux64.zip
Feb 11 19:58:44 flex.releases.ReleaseManager[10060] INFO:  Installing release 0.9.7@alpha started
Feb 11 19:58:49 flex.releases.ReleaseManager[10060] INFO:  Release with version 0.9.7@alpha has been installed to /home/user/.local/share/inexor/releases/0.9.7@alpha
Feb 11 19:58:49 flex.instances.InstanceManager[10060] INFO:  Starting /home/user/.local/share/inexor/releases/0.9.7@alpha/bin/inexor-core-client.exe 31417
Feb 11 19:58:49 flex.instances.InstanceManager[10060] INFO:  client instance 31417 process started with PID 10108
Feb 11 19:58:49 flex.instances.InstanceManager[10060] INFO:  client instance 31417 changes state: stopped ---> started
Feb 11 19:58:50 flex.instances.InstanceManager[10060] INFO:  Created a new GRPC connector
Feb 11 19:58:50 core.client.31417[10060] INFO:  RPC server listening on 0.0.0.0:31417
Feb 11 19:58:50 flex.instances.InstanceManager[10060] INFO:  client instance 31417 changes state: started ---> running
Feb 11 19:58:50 flex.gameserver.IntermissionService[10060] ERROR: Cannot read property 'intermission' of undefined
  err: TypeError: Cannot read property 'intermission' of undefined
      at IntermissionService.onInstanceConnected (/home/user/node_modules/@inexorgame/gameserver/IntermissionService.js:58:30)
      at emitOne (events.js:121:20)
      at Node.emit (events.js:211:7)
      at InstanceManager.transist (/home/user/node_modules/@inexorgame/instances/Instances.js:672:26)
      at connector.connect.then (/home/user/node_modules/@inexorgame/instances/Instances.js:452:26)
      at <anonymous>
Feb 11 19:58:50 flex.instances.InstanceManager[10060] INFO:  Instance 31417 is up and running
Feb 11 19:58:50 core.client.31417[10060] INFO:  RPC Server: New client connected id 0
Feb 11 19:58:51 core.client.31417[10060] INFO:  CefSubsystem::initialize() --> CefInitialize(31417, localhost, 31416, -1, -1)
Feb 11 19:58:51 core.client.31417[10060] INFO:  init: cef: construct InexorCefApp (dimensions: -1x-1)
Feb 11 19:58:51 core.client.31417[10060] INFO:  init: cef: setting subprocess executable_path: /home/user/.local/share/inexor/releases/0.9.7@alpha/bin
Feb 11 19:58:51 core.client.31417[10060] INFO:  [0211/195851:ERROR:browser_main_loop.cc(219)] Running without the SUID sandbox! See https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the sandbox on.
Feb 11 19:58:51 core.client.31417[10060] INFO:  LaunchProcess: failed to execvp:
Feb 11 19:58:51 core.client.31417[10060] INFO:  /home/user/.local/share/inexor/releases/0.9.7@alpha/bin/cef_subprocess.exe
Feb 11 19:58:51 core.client.31417[10060] INFO:  InexorLayerManager::InitializeLayer()
Feb 11 19:58:51 core.client.31417[10060] INFO:  name: hud
Feb 11 19:58:51 core.client.31417[10060] INFO:  url: http://localhost:31416/api/v1/interfaces/hud/index.html?instanceId=31417&host=localhost&port=31416
Feb 11 19:58:51 core.client.31417[10060] INFO:  init: cef: creating layer
Feb 11 19:58:51 core.client.31417[10060] INFO:  name: hud
Feb 11 19:58:51 core.client.31417[10060] INFO:  url: http://localhost:31416/api/v1/interfaces/hud/index.html?instanceId=31417&host=localhost&port=31416
Feb 11 19:58:51 core.client.31417[10060] INFO:  (-1x-1 at 0, 0)
Feb 11 19:58:51 core.client.31417[10060] INFO:  InexorLayer::SetVisibility()
Feb 11 19:58:51 core.client.31417[10060] INFO:  InexorLayer::SetIsAcceptingKeyInput()
Feb 11 19:58:51 core.client.31417[10060] INFO:  InexorLayer::SetIsAcceptingMouseInput()
Feb 11 19:58:51 core.client.31417[10060] INFO:  InexorLayerManager::InitializeLayer()
Feb 11 19:58:51 core.client.31417[10060] INFO:  name: console
Feb 11 19:58:51 core.client.31417[10060] INFO:  url: http://localhost:31416/api/v1/interfaces/console/index.html?instanceId=31417&host=localhost&port=31416
Feb 11 19:58:51 core.client.31417[10060] INFO:  init: cef: creating layer
Feb 11 19:58:51 core.client.31417[10060] INFO:  name: console
Feb 11 19:58:51 core.client.31417[10060] INFO:  url: http://localhost:31416/api/v1/interfaces/console/index.html?instanceId=31417&host=localhost&port=31416
Feb 11 19:58:51 core.client.31417[10060] INFO:  (-1x-1 at 0, 0)
Feb 11 19:58:51 core.client.31417[10060] INFO:  InexorLayer::SetVisibility()
Feb 11 19:58:51 core.client.31417[10060] INFO:  InexorLayer::SetIsAcceptingKeyInput()
Feb 11 19:58:51 core.client.31417[10060] INFO:  InexorLayer::SetIsAcceptingMouseInput()
Feb 11 19:58:51 core.client.31417[10060] INFO:  InexorLayerManager::InitializeLayer()
Feb 11 19:58:51 core.client.31417[10060] INFO:  name: app
Feb 11 19:58:51 core.client.31417[10060] INFO:  url: http://localhost:31416/api/v1/interfaces/client-interface/index.html?instanceId=31417&host=localhost&port=31416
Feb 11 19:58:51 core.client.31417[10060] INFO:  init: cef: creating layer
Feb 11 19:58:51 core.client.31417[10060] INFO:  name: app
Feb 11 19:58:51 core.client.31417[10060] INFO:  url: http://localhost:31416/api/v1/interfaces/client-interface/index.html?instanceId=31417&host=localhost&port=31416
Feb 11 19:58:51 core.client.31417[10060] INFO:  (-1x-1 at 0, 0)
Feb 11 19:58:51 core.client.31417[10060] INFO:  InexorLayer::SetVisibility()
Feb 11 19:58:51 core.client.31417[10060] INFO:  InexorLayer::SetIsAcceptingKeyInput()
Feb 11 19:58:51 core.client.31417[10060] INFO:  InexorLayer::SetIsAcceptingMouseInput()
Feb 11 19:58:51 core.client.31417[10060] INFO:  init: SDL
Feb 11 19:58:51 core.client.31417[10060] INFO:  Adding package directory: /home/user/.local/share/inexor/media/essential/
Feb 11 19:58:51 core.client.31417[10060] INFO:  Adding package directory: /home/user/.local/share/inexor/media/additional/
Feb 11 19:58:51 core.client.31417[10060] INFO:  init: ENet
Feb 11 19:58:51 core.client.31417[10060] INFO:  init: game
Feb 11 19:58:51 core.client.31417[10060] INFO:  init: video
Feb 11 19:58:51 core.client.31417[10060] INFO:  init: gl
Feb 11 19:58:51 core.client.31417[10060] INFO:  Renderer: AMD CARRIZO (DRM 3.1.0 / 4.4.0-53-generic, LLVM 5.0.0) (X.Org)
Feb 11 19:58:51 core.client.31417[10060] INFO:  Driver: 3.0 Mesa 17.2.4
Feb 11 19:58:51 core.client.31417[10060] WARN:  could not load texture texture/inexor/notexture.png
Feb 11 19:58:51 core.client.31417[10060] FATAL: could not find core textures
Feb 11 19:58:51 core.client.31417[10060] INFO:  [0211/195851:ERROR:child_process_launcher.cc(505)] Failed to launch child process
Feb 11 19:58:51 core.client.31417[10060] INFO:  [0211/195851:ERROR:child_process_launcher.cc(505)] Failed to launch child process
Feb 11 19:58:51 core.client.31417[10060] INFO:  [0211/195851:ERROR:child_process_launcher.cc(505)] Failed to launch child process
Feb 11 19:58:51 flex.instances.Connector.localhost.31417.3gv8[10060] ERROR: Synchronize ERROR
Feb 11 19:58:51 flex.instances.Connector.localhost.31417.3gv8[10060] ERROR: 14 UNAVAILABLE: EOF
  err: Error: 14 UNAVAILABLE: EOF
      at createStatusError (/home/user/node_modules/grpc/src/client.js:64:15)
      at ClientDuplexStream._emitStatusIfDone (/home/user/node_modules/grpc/src/client.js:270:19)
      at ClientDuplexStream._receiveStatus (/home/user/node_modules/grpc/src/client.js:248:8)
      at /home/user/node_modules/grpc/src/client.js:784:12
Feb 11 19:58:51 flex.instances.Connector.localhost.31417.3gv8[10060] ERROR: Endpoint read failed
Feb 11 19:58:51 flex.instances.Connector.localhost.31417.3gv8[10060] ERROR: 
  code: 14
  details: "EOF"
  metadata: {"_internal_repr":{}}
Feb 11 19:58:51 flex.instances.InstanceManager[10060] INFO:  client instance 31417 process exited with signal SIGSEGV
Feb 11 19:58:51 flex.instances.InstanceManager[10060] INFO:  Removed connector for instance 31417
Feb 11 19:58:51 flex.instances.InstanceManager[10060] INFO:  client instance 31417 changes state: running ---> started
Feb 11 19:58:51 flex.instances.InstanceManager[10060] INFO:  Removed process for instance 31417
Feb 11 19:58:51 flex.instances.InstanceManager[10060] INFO:  client instance 31417 changes state: started ---> stopped
(1) user ~/i/inexor-core (master)> 
(1) user ~/i/inexor-core (master)> /home/user/node_modules/.bin/inexor-flex 
/home/user/node_modules/rx/dist/rx.js:77
    throw e;
    ^

Error: Cannot find module 'node-rest-client'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/user/node_modules/@inexorgame/treeclient/TreeClient.js:1:78)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
(1) user ~/i/inexor-core (master)>

**Comment by Fohlen** [comment]
Apparently the installation didn't succeed. Can you try `npm i @inexorgame/inexor-flex` again? Or, if necessary (only if really necessary...) use the `-g` flag also

**Comment by FraMecca** [comment]
This is what I get
```

(1) user ~/i/inexor-core (master)> npm i @inexorgame/inexor-flex
npm WARN saveError ENOENT: no such file or directory, open '/home/user/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/user/package.json'
npm WARN user No description
npm WARN user No repository field.
npm WARN user No README data
npm WARN user No license field.

+ @inexorgame/inexor-flex@0.9.3
updated 1 package in 6.86s
user ~/i/inexor-core (master)> /home/user/node_modules/.bin/inexor-flex 
/home/user/node_modules/rx/dist/rx.js:77
    throw e;
    ^

Error: Cannot find module 'node-rest-client'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/user/node_modules/@inexorgame/treeclient/TreeClient.js:1:78)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)

```

**Comment by FraMecca** [comment]
The fact is that I am totally alien to npm and the installation page provides no instruction for it.

The node errors makes no sense as well.

**Comment by Fohlen** [comment]
@FraMecca I see. The error here tells you that it didn't successfully install `@inexorgame/inexor-flex`. The package `node-rest-client` is missing .. therefore it will not start. Do you mind joining us on Riot so we can give you realtime support 👍 would be amazing!

**Comment by Croydon** [comment]
I can confirm the latest problems as I'm running into it myself now.

**Comment by Croydon** [comment]
And after several minutes running flex in this broken state seven windows with this error come up:

![error](https://user-images.githubusercontent.com/1593194/36288591-c92ebb1c-12bb-11e8-99dd-7262b68fc030.PNG)

**Comment by Croydon** [comment]
Hi @FraMecca, they last error your encountered is now fixed.

We, however, require now [Yarn](https://yarnpkg.com/en/docs/install)

You can try to install Yarn and execute then `yarn global add @inexorgame/inexor-flex` followed by `inexor-flex`.

If you encounter new problems please open new issues.
