### ISSUE TITLE
Rolling release of Inexor Flex

### ISSUE THREAD

**Issue by aschaeffer** [inexorgame/inexor-core#518]
Almost the same steps as for Inexor Core:

- [x] Travis builds Inexor Flex
- [x] For each push on the master branch
  - [x] A new tag is created
  - [x] Travis publishes the npm package to https://github.com/inexorgame/inexor-flex/releases
  - [x] Travis publishes the npm package to https://www.npmjs.com/package/@inexorgame/inexor-flex
  - ~~A snap package is created and uploaded to https://github.com/inexorgame/inexor-flex/releases~~
  - ~~A debian package is created and uploaded to https://github.com/inexorgame/inexor-flex/releases~~ (Croydon: This should be part of #519)

**Comment by Fohlen** [comment]
We should use [snapcraft build](https://build.snapcraft.io) because

- it provides CI specifically tailored for snapcraft
- more importantly: it can automatically publish a new version to the Ubuntu Store

=> Imagine how awesome that would be. Inexor finally in Ubuntu Store 👍

**Comment by Croydon** [comment]
One format doesn't exclude the other.

I will work at Flatpak support at some point.

**Comment by Croydon** [comment]
https://github.com/inexorgame/inexor-flex/pull/25

**Comment by Croydon** [comment]
Done by https://github.com/inexorgame/inexor-flex/pull/25 and many follow up commits.
