### ISSUE TITLE
Write a generic "application" framework for flex

### ISSUE THREAD

**Issue by Fohlen** [inexorgame/inexor-core#528]
Something like [Django Apps](https://docs.djangoproject.com/en/1.11/ref/applications/#module-django.apps) have proven to be extremly reliable and useful in the long term.
Currently the wiring of our modules is sorta random and only possible for the `v1` API.
The "flex framework" should wire all installed apps and then inject those into the API's so that they can be used much more commonly.
This can also solve async issues because in Django the `INSTALLED_APPS` have a fixed, deterministic load order.

**Comment by aschaeffer** [comment]
I don't see the problem and I still prefer the dependency injection pattern.

* Flex already has a registry of running components (see `/src/context/`)
  * The components are wired together in the application context _at runtime_ automatically
  * Each component can use other components by getting them over the application context
* The wiring is not random at all, it uses life cycle phases:
  * first construct all components (constructor)
  * then set all dependencies of all components (setDependencies)
  * then run startup tasks of all components (afterPropertiesSet)

The big benefit is that all components are loosely coupled.

The most major issue is that the components have to be declared by code currently. This could be done using a config file in the future.

**Comment by Fohlen** [comment]
Okay. Closing this.
