### ISSUE TITLE
Graphics issue on Intel GMA4500M (invisible geometry)

### ISSUE THREAD

**Issue by rv4Flyver** [inexorgame/inexor-core#539]
Hello,
I've experiencing problems on a laptop with Intel GMA4500M while Cube 2 Sauerbraten works fine:
![1978412252635b05ed684e3f95c3b40495d6e44f21bf1f14d7 pimgpsh_fullsize_distr](https://user-images.githubusercontent.com/5278418/33469709-81e92684-d675-11e7-9ea6-f128bbc7bbdf.png)

**Comment by IceflowRE** [comment]
Could you add a screenshot of the problem from RE?

**Comment by a-teammate** [comment]
Does Sauerbraten also work fine with shaders enabled? Are the settings the same?

**Comment by rv4Flyver** [comment]
Sauerbraten works well with all shaders enabled.

**Comment by deathstar** [comment]
Intel are known for their processors, not graphics cards.

Unfortunately, this seems like a pretty bad bug. Also, that graphics card chipset is integrated. :( 

What a bummer.

**Comment by Croydon** [comment]
@rv4Flyver Are you using the latest Collect edition (there were some patches as download packages) or the svn version?

**Comment by rv4Flyver** [comment]
@Calinou, frankly speaking I do not know as I've downloaded it from https://inexor.org/download

**Comment by a-teammate** [comment]
Ah no @Croydon meant the Sauerbraten version you were taking as comparison.
But it's alright, won't make a difference probably.

It won't be fixed too soon though, since the system beneath changes anyways.

**Comment by Calinou** [comment]
That Intel IGP is *very* old and its drivers are really bad (it doesn't really support OpenGL 2.x anywhere now); newer Intel graphics (starting from Haswell) are much better in that regard.

**Comment by Croydon** [comment]
Official it should support OpenGL 2.1.
@rv4Flyver What operating system and version are you using?

**Comment by Croydon** [comment]
Closing because of missing feedback.

**Comment by rv4Flyver** [comment]
> Official it should support OpenGL 2.1.
> @rv4Flyver What operating system and version are you using?
It was Windows 7 x64.

Sorry for the late response, I've got a new laptop and have no access to old one atm, so the problem is no more relevant for me. And on the other hand you also have other tasks that are more important that support of outdated hardware.
