### ISSUE TITLE
Get us and all of our Conan dependencies compatible with Conan >= 1.0.0

### ISSUE THREAD

**Issue by Croydon** [inexorgame/inexor-core#547]
This at least requires to get updates for SDL2/SDL2_image, more might be broken.

**Comment by Croydon** [comment]
https://github.com/lasote/conan-sdl2/issues/14

**Comment by a-teammate** [comment]
## SDL2
https://github.com/bincrafters/conan-sdl2/
is a compliant from-scratch approach. Looks very good. not yet ready, though.

trying to fix this i made just minor changes and arrived here:
https://github.com/a-teammate/conan-sdl2/tree/release/2.0.5 (not yet uploaded though)

## SDL2_image
I made a quick fix in
https://github.com/a-teammate/conan-sdl2_image/tree/release/2.0.1
which is using libpng and libjpeg-turbo from the bincrafters remote!

I'm hoping that bincrafters will do a from-scratch version here as well.

@Croydon: did you already upload the fixed CEF and Protobuf recipes? (ConfigureEnvironment was dead code for them)
Could you upload the SDL2_image and SDL2 from my repo to the inexor remote and maybe the libjpeg turbo and libpng ones as well? Or maybe we should just add the bincrafters remote. They seem to be doing a pretty good job.

**Comment by Croydon** [comment]
> @Croydon: did you already upload the fixed CEF and Protobuf recipes? (ConfigureEnvironment was dead code for them)

yes, of course

> Could you upload the SDL2_image and SDL2 from my repo to the inexor remote and maybe the libjpeg turbo and libpng ones as well? Or maybe we should just add the bincrafters remote. They seem to be doing a pretty good job.

Reminder: Our CI is working the way that it copies every recipe we use over to our own repository, so that nobody needs to add more repositories other than ours.
Yes, I will upload the changed SDL packages. Thanks for removing ConfigureEnvironment.

Could you please create pull requests in lasotes repositories?

**Comment by a-teammate** [comment]
> Could you please create pull requests in lasotes repositories?
Im not so sure whether they get accepted (since lasotes repo seems dead), but yes Ill do :)

**Comment by a-teammate** [comment]
What is missing for the CI?

**Comment by Croydon** [comment]
It's hard to tell what is missing overall, but right now it stucks with grpc: https://travis-ci.org/inexorgame/inexor-core/jobs/326667423#L2889

**Comment by Croydon** [comment]
Fixed with #552.
