### ISSUE TITLE
Add spellchecker CLI for blog-data

### ISSUE THREAD

**Issue by Croydon** [inexorgame/inexor-core#551]
https://github.com/tbroadley/spellchecker-cli

**Comment by zahiryahya1** [comment]
I would like to work on implementing this. How do you want the workflow to behave?

**Comment by Croydon** [comment]
The minium requirements for this would be:

  * Run Travis on every push on _all_ md files
    * create a travis.yml in the root directory of https://github.com/inexorgame/blog-data/
    * you can likely take this as an example: https://github.com/inexorgame/inexor-flex/blob/master/.travis.yml
    * Travis documentation: https://docs.travis-ci.com
  * A single Travis job is required (choose Node.js 8 as the runtime)
  * This job installs spellchecker-cli via npm
  * This job runs spellchecker-cli
  * If spellchecker-cli finds an typo/grammar mistake the Travis job should fail, (therefore reporting "failed" back to GitHub automatically)
    * this is the expected default behaviour of the script and no steps should be required, if this is not the case you can let Travis fail be some return code
  * it should use en-US as the dictionary
  
Nice-to-have but not requirements for this issue:

  * there is a good chance that we get some errors because of some very technical or Inexor-related terms, if necessary this words should get ignored in some way or be added to some personal dictionary
    * when a personal dictionary is used this should be in the blog-data repository as well (root directory)
  * we don't need to check every file on every push; only check .md files, which did change in the respective commit (get them with some git command)


I have enabled Travis for the repository, therefore I would recommend to 
  * fork the repo 
  * create a personal/feature branch
  * create a pull request with "WIP" (Work in progress) in the title, this causes Travis to run and provides you feedback and at the same time we know that your work isn't finished yet

**Comment by zahiryahya1** [comment]
I got the basic functionality working. What do you want me to do with the current misspelled or technical words?

**Comment by Croydon** [comment]
@zahiryahya1 
I see that you have already created a dictionary file with a list of words. If you add "Inexor", "Sauerbraten", "CMake" and "GitHub" to it it's fine for the beginning. I will have a look at the upcoming mistakes afterwards then.

You also shouldn't let the job fail after a single file with mistakes. Please output all mistakes of all files before letting the job fail.

Good job so far!

**Comment by a-teammate** [comment]
I think it is alright to display them in the CI before erroring.

Then after seeing the PR's travis job failed, one would check in the log of travis why it fails, and see the errors listed together with the line and the row of the misspelled word:)

**Comment by Croydon** [comment]
Done via https://github.com/inexorgame/blog-data/commit/5a9ff04e341623844fae4ac25f93ab7de052039c / https://github.com/inexorgame/blog-data/pull/9
