### ISSUE TITLE
Organize Wiki according to project structure

### ISSUE THREAD

**Issue by a-teammate** [inexorgame/inexor-core#554]
Since the [frontpage of the Wiki](https://github.com/inexorgame/inexor-core/wiki) is redesigned, we could improve the usability of the wiki with a further step:
We could make it so that the big image which summarizes the structure could act as a guidance through the wiki.

It would clearify the navigation, if we renamed all wiki sites according to a pattern.
Suggestion: `[module] wiki page name`
e.g. `[Creator] Visual Scripting System`

and for those of the "Source Framework" and "Development Environment", the pattern could be modified: `[Source Framework] Logging`

~~I.e. if you hover over a module, you see a quick summary what it is.
And if you click on a module, it could lead us towards a dedicated wiki page which provides a quick introduction and a list of wiki pages of that module.~~

**EDIT:**

Although the svg image format is able to contain links and "title"-subelements (which should become visible as infoboxes in usual html) it is not working in the github wiki.
Some other solution is needed. As idk how to support ImageMaps in the github wiki, im not so sure how to include a "link-sensitive" image in the wiki..
Maybe just keep the links separately in a list next to the image.

**Comment by MartinMuzatko** [comment]
Is this still valid @a-teammate ?

**Comment by Fohlen** [comment]
Seems to me like the recent move of the site makes this obsolete.
