### ISSUE TITLE
Hide cef_subprocess console window

### ISSUE THREAD

**Issue by IAmNotHanni** [inexorgame/inexor-core#566]
Multiple CEF sub processes will open a console window when Inexor has been started.

![cef_subprocess](https://user-images.githubusercontent.com/7914428/36356796-703a9cc2-14f7-11e8-8934-d12b24107555.jpg)

[MSDN FreeConsole function](https://docs.microsoft.com/en-us/windows/console/freeconsole)  
[Stackoverflow](https://stackoverflow.com/questions/18260508/c-how-do-i-hide-a-console-window-on-startup)

**Comment by IAmNotHanni** [comment]
This distracts the user. I think these windows should be hidden. The processes shouldn't terminate of course.

**Comment by a-teammate** [comment]
This is currently not a bug, just development state.
(For logging purpose, but we can also just look in the inexorcef.log)

We can hide these windows by compiling it with a different windows subsystem.
I have a untested commit which solves this, if you are willing to test it on windows @IAmNotHanni and maybe try to fix the edges which may not be working straight away, I can upload it.

**Comment by IAmNotHanni** [comment]
Create a pull request pls so I can review.

**Comment by a-teammate** [comment]
I currently don't have time for a PR (at most it can be untested).. Could you test it? and fix eventually the fuckups?
It is simple: remove CONSOLE_APP in the cmakelists.txt.
afterwards the main() function wont be found, since on windows it is named differently. thats why the other lines are there.

**Comment by IAmNotHanni** [comment]
Ok I'm on it.

**Comment by IAmNotHanni** [comment]
@a-teammate Why don't we just link it to another windows subsystem ? I'm sure you mentioned this lately.

**Comment by IAmNotHanni** [comment]
This pull request will fix it: https://github.com/inexorgame/inexor-core/pull/577
Awaiting confirmation/review.
