### ISSUE TITLE
Maybe change gameident in mapformat

### ISSUE THREAD

**Issue by movabo** [inexorgame/inexor-core#572]
So, as written here: https://incoherency.co.uk/interest/sauer_map.html
The mapformat has a game ident. The site (which is not a real documentation) says

> This is a string to identify which game the map is intended for. It consists of a single byte to give the length of the string, followed by a string of that length, plus a zero-terminating byte. For normal Sauerbraten, this string is just "fps". 

So I'm not sure if this type is meant for things like "fps" or "rpg" (which the original value uses) or for game (like "inexor").
The original value suggests the first case, the site suggests the second case.

So maybe it might be an option to change that to "inexor" this would also allow to start with map version "1" (instead of currently.. 40?) which (at least for me) seems a little nicer.

**Comment by IAmNotHanni** [comment]
As far as I know @a-teammate should be the one to talk to since he has worked on the map format.

**Comment by Croydon** [comment]
I don't think we should do this right now. It has literally no advantage as long as we don't change the map format in another way.

**Comment by a-teammate** [comment]
I agree, as #53 does go far beyond just changing a value :)

**Comment by a-teammate** [comment]
I will close this, since we will solve this probably with #53, as soon as we need it for adding more features.
