### ISSUE TITLE
No local edit mode possible

### ISSUE THREAD

**Issue by movabo** [inexorgame/inexor-core#573]
Currently (when using the windows installer; after a completely fresh installation) when typing `map test` or `newmap` no map is loaded. This is a major drawback as then you need a server to actually edit.

This means, that you own your own server or that mapping servers are hosted, thus relying on others and that means, that you **need** an internet connection.

I think for no gamemode an offline implementation is not really useful (as it really does not make any fun) **except** for edit mode and there it is actually essential.

**Comment by Croydon** [comment]
All local modes are needing a local server now. Maybe you didn't start it via the flex-ui?

It should start automatically, so maybe this is the actuall bug here.

**Comment by movabo** [comment]
I tried but it didn't work.

I think if this happens (at least for the commands `map <xyz>` and `newmap`) a server should be started automatically (with this map) or at least a dialogue should appear to automatically start one.

**Comment by IAmNotHanni** [comment]
@movabo The server has to be started manually via Inexor flex web interface at the moment.
See my answer in #574 .
But I think the server should be started automatically once you open Inexor. I will make a ticket for this.

**Comment by IAmNotHanni** [comment]
This was fixed by https://github.com/inexorgame/inexor-flex/pull/26.
