### ISSUE TITLE
Start Inexor server automatically when loading maps locally

### ISSUE THREAD

**Issue by IAmNotHanni** [inexorgame/inexor-core#575]
In case you didn't notive: **singleplayer has been removed**.
In order to load a map for example you have to start Inexor's server via flex web user interface:
Open `localhost:31416` in your browser.

To start a server in Inexor flex, go to "instances" and click "start":

![error: could not find image!](https://raw.githubusercontent.com/inexorgame/visualisations/e475eb76f10a16a8d594ee5ad863bee335ac9ccc/wiki/Inexor_FLEX_start_default_production_server.jpg)

Then click "connect":

![error: could not find image!](https://raw.githubusercontent.com/inexorgame/visualisations/e475eb76f10a16a8d594ee5ad863bee335ac9ccc/wiki/Inexor_FLEX_connect_to_default_production_server.jpg)

# Confusion

As tickets #574 and #573 show this is confusing. Start Inexor's server automatically when loading a map in "singleplayer".

**Comment by a-teammate** [comment]
If you change autostart and autoconnect to `true` it will always start a server:
https://github.com/inexorgame/inexor-flex/blob/master/config/client/instances.toml#L11
Do you mind providing a PR for that?

**Comment by IAmNotHanni** [comment]
Since I just got my build enviroment working again I will.

**Comment by Croydon** [comment]
Fixed by https://github.com/inexorgame/inexor-flex/pull/26
