### ISSUE TITLE
Fix Flex tests

### ISSUE THREAD

**Issue by Croydon** [inexorgame/inexor-core#579]
Mocha tests are broken.

My guess is that it somehow tries to run internal tests for OUR deps (e.g. tests for cors and tests for mocha itself...).

This causes it to require a lot of additional deps:

mocha:
`    "tape": "4.9.0",
    "supertest": "1.2.0",
    "should": "13.2.1",
    "connect": "~3.6.6"`

cors:
`    "basic-auth-connect": "^1.0.0",`

But eventually it fails anyway: https://ci.appveyor.com/project/inexorgame/inexor-flex/build/1.0.396/job/x1udyjgrg3doshl5#L305

Tests can be executed by `yarn test`

Evidence (these deps are required..)
https://github.com/expressjs/cors/commit/98f2ef4b7d24bd5b83272c7c275271c808fc4cb2
https://github.com/expressjs/cors/commit/8a448ccbf888ea8148c3608d48f3b093c56da98b

**Comment by Fohlen** [comment]
For whatsoever reasons the `node_modules` folders are now inside the module folders.. which the glob doesn't ignore.
