### ISSUE TITLE
Fix Flex jsdoc warnings: the Private tag does not permit a value

### ISSUE THREAD

**Issue by Croydon** [inexorgame/inexor-core#581]
The following warnings need to get fixed:

> jsdoc -c .jsdoc.json
WARNING: The @private tag does not permit a value; the value will be ignored. File: index.js, line: 9
WARNING: The @private tag does not permit a value; the value will be ignored. File: index.js, line: 16
WARNING: The @private tag does not permit a value; the value will be ignored. File: ReleaseManager.js, line: 315
WARNING: The @private tag does not permit a value; the value will be ignored. File: ReleaseManager.js, line: 321
WARNING: The @private tag does not permit a value; the value will be ignored. File: ReleaseManager.js, line: 356
WARNING: The @private tag does not permit a value; the value will be ignored. File: ReleaseManager.js, line: 362
WARNING: The @private tag does not permit a value; the value will be ignored. File: ReleaseManager.js, line: 428
WARNING: The @private tag does not permit a value; the value will be ignored. File: ReleaseManager.js, line: 434
WARNING: The @private tag does not permit a value; the value will be ignored. File: ReleaseManager.js, line: 448
WARNING: The @private tag does not permit a value; the value will be ignored. File: ReleaseManager.js, line: 453
WARNING: The @private tag does not permit a value; the value will be ignored. File: ReleaseManager.js, line: 466
WARNING: The @private tag does not permit a value; the value will be ignored. File: ReleaseManager.js, line: 481
WARNING: The @private tag does not permit a value; the value will be ignored. File: ReleaseManager.js, line: 537
WARNING: The @private tag does not permit a value; the value will be ignored. File: ReleaseManager.js, line: 546
WARNING: The @private tag does not permit a value; the value will be ignored. File: ReleaseManager.js, line: 699
WARNING: The @private tag does not permit a value; the value will be ignored. File: ReleaseManager.js, line: 709

## Recommended steps:
1) Fork flex repository https://github.com/inexorgame/inexor-flex and clone your fork 
2) Make sure you have the [Yarn](http://yarnpkg.com/) package manager installed
3) Execute `yarn install` in a terminal within the flex repository
4) Locate the file and understand the warning
5) Fix the warnings, verify that it's fixed by running `yarn run docs`
6) Create a pull requests with your changes here: https://github.com/inexorgame/inexor-flex/pulls

Let us know if you are having any questions or troubles 😄

**Comment by Fohlen** [comment]
This warning can be safely ignored.
`jsdoc` intends private values or methods not to be documented. We think this is stupid and therefore we do add documentation sometimes. The resulting warning is this.

**Comment by Croydon** [comment]
Please add the org:wontfix label if you are closing issues as wontfix.
