### ISSUE TITLE
Remove all publically published @inexorgame/xyz packages

### ISSUE THREAD

**Issue by Croydon** [inexorgame/inexor-core#582]
Mark all public published @inexorgame/xyz packages as deprecated **(except @inexorgame/inexor-flex of course**).

We don't need them any longer and it's a confusing mess.

Let's deprecate them now so that remaining users are getting warnings.

I suggest to remove them finally with our 0.10.0 release.

**Comment by Fohlen** [comment]
If packages are not actually used any longer we can also unpublish them, rather than marking them as deprecated. This probably depends on #580

**Comment by Croydon** [comment]
I would like to have them deprecated for a while before removing. In theory I have marked them now as deprecated. However, with no feedback from the cli nor any visual hints on the website, I have no idea if it works...

For removage we need to contact the support, since they have a stupid policy, which only allows self-deletions within 24hours for every published version.

**Comment by Croydon** [comment]
I contacted the support.

**Comment by Croydon** [comment]
Support deleted all packages except inexor-flex https://www.npmjs.com/org/inexorgame
