### ISSUE TITLE
Fix doxygen generated docs

### ISSUE THREAD

**Issue by a-teammate** [inexorgame/inexor-core#596]
Currently the docs are not displayed at all: https://docs.inexor.org/core/index.html

**Comment by a-teammate** [comment]
We could also use a solution like that: https://htmlpreview.github.io/?https://github.com/OlafvdSpek/ctemplate/blob/master/doc/index.html
no need to host the docs ourselves.

**Comment by aschaeffer** [comment]
We could use travis and github gh-pages:
https://gist.github.com/vidavidorra/548ffbcdae99d752da02

@Croydon Would it be possible to integrate this into our travis pipeline?

**Comment by Croydon** [comment]
It is live now again on https://docs.inexor.org/core/master/
