### ISSUE TITLE
Starting to get working - roadmap. Next up: meeting on 28th August 2018

### ISSUE THREAD

**Issue by MartinMuzatko** [inexorgame/inexor-core#607]
We have somewhat of a roadmap.

@IAmNotHanni continue working on the entity system
@aschaeffer with @a-teammate works on core module loader system
@martinmuzatko will have a look at how we can modularize flex to mirror the modules on scripting side.

Agenda for next meeting: https://hackmd.io/s/HytxvvX8Q

last meeting: #604

**Comment by Croydon** [comment]
@MartinMuzatko Please add the meeting label next time :smile:
