### ISSUE TITLE
Hackathon 2018 ⅠⅠ

### ISSUE THREAD

**Issue by MartinMuzatko** [inexorgame/inexor-core#608]
I'm happy to announce that I'll host the next hackathon this year!

I noted down below what we need in order to make this hackathon successful :)

- [x] Settle for a date
- [x] Location (more below)
- [x] Prepare an agenda
- [x] Tshirts! Self-made - we have a t-shirt press at home (We need a design!)
- [ ] ~Write a blogpost~

## Date

The Hackathon will happen from **23rd** to **25th** of November.
Preview of Agenda: https://hackmd.io/s/r12wcOXo7

## Location
Early this year me and my partner moved into a new home (still under construction). As already offered earlier this year, we would like to offer to hold this years (now) second hackathon.

**Address:**
[71229 Warmbronn, Planstraße 19](https://goo.gl/maps/KrrNxMKyK1B2)

![image](https://user-images.githubusercontent.com/2950505/44236967-10eb3980-a1af-11e8-804e-5e3a10f23538.png)
(More photos to come)

### Accomodation

We have mattresses, blankets and pillows for up to 8-9 people (excluding us).
Depending on how much space you need and how cuddly you are:

**Guestroom/Chillout**
- 1 large mattress for 2
- 3 small mattresses for 1
- 1 Hammock

**Livingroom**
- 1 large L shaped sofa for 2~3

**Musicroom**
- 1 small sofa (comfy!) for 1

- a couple of isomats

There is plenty of space (I would think in total for up to 20 people) and also floor heating in the first floor <3
If possible, bring your own pillow and blanket, we only have some light blankets, but covers for all beds.

It is our home - we trust you to handle it in an orderly manner.

### Food

We will offer vegetarian and meat dishes. If you love, we can cook together. We do catering for our own events as a hobby, so we have plenty of experience in that matter :)

### Participation fee

We will split the bills evenly and add a few euros for accomodation/house costs (electricity, water, etc).
Participation during the day is free of course, but we will also distribute a few snacks and drinks if possible.

By average, I could imagine that 7-10 euro per **person** per **day** is fair for 
- 2x dinner (fr, sat)
- 2x breakfast (sat, sun)
- softdrinks

### T-shirt

As earlier mentioned: We have our own t-shirt press. We need to buy t-shirts in advance that are able to be (sublimentationsfarbendruck) printed.

We could also come up with a little design. Otherwise, if you already have ideas, please share them!

That's all for now! Hope to see you at the Hackathon.

(Appended by @Croydon:)

### Expected participants 
  * @MartinMuzatko
  * @aschaeffer  
  * @a-teammate 
  * @Fohlen  
  * @Croydon 
  * @westernheld 
  * @koppiman 
  * @IAmNotHanni 
  * @movabo (saturday+sunday)
  * Pum Amurcat 

### Protocol
https://hackmd.io/9ZM1iB4XRCuImZA3ljSfzQ (some parts are in German right now, translation coming (maybe))

**Comment by IAmNotHanni** [comment]
This is awesone!

**Comment by sdegueldre** [comment]
Is this a date?

**Comment by MartinMuzatko** [comment]
Date as in time and date. meetup, appointment.

**Comment by Fohlen** [comment]
Thanks for bringing this to live @MartinMuzatko 
After a longer time of inactivity I decided that I will need to definitely show up on the Hackathon! Looking forward for it <3

**Comment by sdegueldre** [comment]
I was making a bad joke about the word date, don't mind me. I hope to be able to come and get involved in this project, looks like fun!

**Comment by IAmNotHanni** [comment]
I am so excited about this.
Thanks @MartinMuzatko !

**Comment by Croydon** [comment]
That doodle is only about tshirts, there should be a separate list with people who want to come.

Count me in 😃

**Comment by MartinMuzatko** [comment]
The original one is already closed that was used to find a date: https://doodle.com/poll/3wx2k6upykdgqd2u

But it is good to know you will come :)

**Comment by Croydon** [comment]
Yes, but this was a doodle to a find a date. Give people a chance to jump in now for the final days. We already have at least one person here in this issue who wants to come who isn't in the doodle (as far as I can see it).

**Comment by MartinMuzatko** [comment]
It is open again

**Comment by Croydon** [comment]
Hey @sdegueldre, will we see you in the next days? 😄

**Comment by sdegueldre** [comment]
I'm afraid not, life got in the way and I don't have a car to swing by unfortunately, hope you all have a fun and productive weekend!

**Comment by Croydon** [comment]
> I'm afraid not, life got in the way and I don't have a car to swing by unfortunately,

Sorry, to hear that, but maybe next time :) 

> hope you all have a fun and productive weekend!

thanks!

**Comment by sdegueldre** [comment]
> Sorry, to hear that, but maybe next time :)

I would like that! If you're hanging out on a discord or some such let me know, i'd love to take part despite the distance :)

**Comment by Croydon** [comment]
A huge 
# THANK YOU 
to Misan and Pum for organizing and providing the place for this Hackathon!

It was productive and brilliant.

To all: Don't forget to upload possible missing documentation and links to existing PADs within the [main Protocol pad](https://hackmd.io/9ZM1iB4XRCuImZA3ljSfzQ).
