### ISSUE TITLE
Fix capture mode respawn time

### ISSUE THREAD

**Issue by Croydon** [inexorgame/inexor-core#64]
I totally support the change of the respawn time in capture to 10 seconds instead of the current 5s for the named reasons:

http://cubeengine.com/forum.php?action=display_thread&thread_id=2666http://cubeengine.com/forum.php?action=display_thread&thread_id=2666

What do you all think about that?

**Comment by Fohlen** [comment]
I'd say we should not change this for now until we have #339 and then we can try it experimentally

**Comment by a-teammate** [comment]
We will have #339 soon, any more thoughts?

I would be in favor, since capture was one of the most popular modes and seemed to have suicided after that change.

**Comment by Fohlen** [comment]
It was decided and implemented on the hackathon. Go for it into master branch.

**Comment by Croydon** [comment]
https://github.com/inexorgame/inexor-core/commit/de412cea0902d54c4a3b58d76dfbbb20f62aa3de

**Comment by Croydon** [comment]
Seems like writing (close #64) within a PR title doesn't work any longer.
Needs be written in the pr body now.

Fixed by #556
