### ISSUE TITLE
Better HUD

### ISSUE THREAD

**Issue by Fransje** [inexorgame/inexor-core#98]
The HUD in vanilla Sauer misses some stuff that should absolutely be there, IMO. That is why more experienced players use modified clients, but newcomers don't know about that. They also deserve these HUD updates:
    - a game timer. Every ffa player will agree :)
    - a score widget. ComEd has this ( http://comed.sauerworld.org/documentation/ ). It shows your own score (frags) or that of your team (flags, base points, frags, skulls). It also shows the score of your enemy (in duels) and the score of the enemy team (if there is only one other team). It is a little bit hard to explain when there are more enemies (or enemy teams): if you (or your team) have the highest score, the team or player with the second highest score is displayed, next to your own score of course. When you (or your team) do not have the highest score, the player or team with the highest score is displayed, next to your own score.
    - an ammo bar. At first I didn't think this would be necessary, but in item modes it is really useful. A good example of such an ammo bar is also in ComEd (check link above). Quake Live has it too. There should be an option to disable it in insta.

A very cool thing would be if the HUD was technically a GUI. That would mean that you could script your HUD in HTML or whatever Inexor uses for the GUI. A default HUD script should be included of course. I don't know if this is possible though.

**Comment by aschaeffer** [comment]
Hi Fransje,

you are right and we want to improve the HUD, too. We've seen that there are a lot of sauerbraten mods which customize the user interface of the client. One of the goals of inexor is to force the

We are working on the CEF (Chromium embedded framework) integration right now (see #50). The goal is to create a better, more flexible and customizable user interface. This video shows a first prototype of the main menu in HTML and JavaScript:

https://www.youtube.com/watch?v=eFMS_bXPDr8

Once we've finished integrating CEF we surely will go on your suggestion (game timer, score widget and ammo bar).

**Comment by Fransje** [comment]
Ah thanks for the video, I had heard about CEF and got very curious, but I had never seen it working. This looks very smooth. Great work!

**Comment by IAmNotHanni** [comment]
SuperTux and I have developed some sort of "frag hud".
These things are very famous in various shooters.

http://gstf-clan.de/downloads/fraghud.png

**Comment by MartinMuzatko** [comment]
Currently working on UI Mockups/Sketch Layouts.

Looking for a main menu layout that is flexible enough to extend + giving a great overview.
I wanted to open up an issue on https://github.com/inexor-game/ui-prototype, where this issue might fit. They are only open for PRs though.
Currently working on UI Mockups/Sketch Layouts.

Looking for a main menu layout that is flexible enough to extend + giving a great overview.
I wanted to open up an issue on https://github.com/inexor-game/ui-prototype, where this issue might fit. They are only open for PRs though.

# Main Menu

## Steam Like (Library) 

![image](https://cloud.githubusercontent.com/assets/2950505/14770932/51d3fc7e-0a7c-11e6-9d0c-a248640423a2.png)

Comparable to [Steam](http://static.giantbomb.com/uploads/original/2/29874/2438982-like+this.jpg)
# Main Menu

## Steam Like (Library) 

![image](https://cloud.githubusercontent.com/assets/2950505/14770932/51d3fc7e-0a7c-11e6-9d0c-a248640423a2.png)

Comparable to [Steam](http://static.giantbomb.com/uploads/original/2/29874/2438982-like+this.jpg)

**Comment by MartinMuzatko** [comment]
IGC just proposed a Dashboard
![image](https://cloud.githubusercontent.com/assets/2950505/14901360/28e4368c-0d95-11e6-97a3-34d611d897ba.png)

**Comment by Croydon** [comment]
Closed as duplicate in favor of #312
